namespace GUI.foodcourt
{
    partial class f_themdmvean
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.dataLayoutControl1 = new DevExpress.XtraDataLayout.DataLayoutControl();
            this.Root = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlGroup1 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.dmveanBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.ItemForidve = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForghichu = new DevExpress.XtraLayout.LayoutControlItem();
            this.idveSpinEdit = new DevExpress.XtraEditors.SpinEdit();
            this.ghichuTextEdit = new DevExpress.XtraEditors.MemoEdit();
            this.emptySpaceItem1 = new DevExpress.XtraLayout.EmptySpaceItem();
            ((System.ComponentModel.ISupportInitialize)(this.dataLayoutControl1)).BeginInit();
            this.dataLayoutControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.Root)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dmveanBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForidve)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForghichu)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.idveSpinEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ghichuTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem1)).BeginInit();
            this.SuspendLayout();
            // 
            // dataLayoutControl1
            // 
            this.dataLayoutControl1.Controls.Add(this.idveSpinEdit);
            this.dataLayoutControl1.Controls.Add(this.ghichuTextEdit);
            this.dataLayoutControl1.DataSource = this.dmveanBindingSource;
            this.dataLayoutControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dataLayoutControl1.Location = new System.Drawing.Point(0, 28);
            this.dataLayoutControl1.Name = "dataLayoutControl1";
            this.dataLayoutControl1.Root = this.Root;
            this.dataLayoutControl1.Size = new System.Drawing.Size(418, 91);
            this.dataLayoutControl1.TabIndex = 4;
            this.dataLayoutControl1.Text = "dataLayoutControl1";
            // 
            // Root
            // 
            this.Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            this.Root.GroupBordersVisible = false;
            this.Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlGroup1});
            this.Root.Name = "Root";
            this.Root.Size = new System.Drawing.Size(418, 91);
            this.Root.TextVisible = false;
            // 
            // layoutControlGroup1
            // 
            this.layoutControlGroup1.AllowDrawBackground = false;
            this.layoutControlGroup1.GroupBordersVisible = false;
            this.layoutControlGroup1.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.ItemForidve,
            this.ItemForghichu,
            this.emptySpaceItem1});
            this.layoutControlGroup1.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup1.Name = "autoGeneratedGroup0";
            this.layoutControlGroup1.Size = new System.Drawing.Size(398, 71);
            // 
            // dmveanBindingSource
            // 
            this.dmveanBindingSource.DataSource = typeof(DAL.dmvean);
            // 
            // ItemForidve
            // 
            this.ItemForidve.Control = this.idveSpinEdit;
            this.ItemForidve.Location = new System.Drawing.Point(0, 0);
            this.ItemForidve.Name = "ItemForidve";
            this.ItemForidve.Size = new System.Drawing.Size(161, 24);
            this.ItemForidve.Text = "Id Vé";
            this.ItemForidve.TextSize = new System.Drawing.Size(37, 13);
            // 
            // ItemForghichu
            // 
            this.ItemForghichu.Control = this.ghichuTextEdit;
            this.ItemForghichu.Location = new System.Drawing.Point(0, 24);
            this.ItemForghichu.Name = "ItemForghichu";
            this.ItemForghichu.Size = new System.Drawing.Size(398, 47);
            this.ItemForghichu.Text = "Ghi Chú";
            this.ItemForghichu.TextSize = new System.Drawing.Size(37, 13);
            // 
            // idveSpinEdit
            // 
            this.idveSpinEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dmveanBindingSource, "idve", true));
            this.idveSpinEdit.EditValue = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.idveSpinEdit.Location = new System.Drawing.Point(52, 12);
            this.idveSpinEdit.Name = "idveSpinEdit";
            this.idveSpinEdit.Properties.Appearance.Options.UseTextOptions = true;
            this.idveSpinEdit.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Far;
            this.idveSpinEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.idveSpinEdit.Properties.EditValueChangedFiringMode = DevExpress.XtraEditors.Controls.EditValueChangedFiringMode.Default;
            this.idveSpinEdit.Properties.Mask.EditMask = "n0";
            this.idveSpinEdit.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.idveSpinEdit.Size = new System.Drawing.Size(117, 20);
            this.idveSpinEdit.StyleController = this.dataLayoutControl1;
            this.idveSpinEdit.TabIndex = 6;
            // 
            // ghichuTextEdit
            // 
            this.ghichuTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.dmveanBindingSource, "ghichu", true));
            this.ghichuTextEdit.Location = new System.Drawing.Point(52, 36);
            this.ghichuTextEdit.Name = "ghichuTextEdit";
            this.ghichuTextEdit.Size = new System.Drawing.Size(354, 43);
            this.ghichuTextEdit.StyleController = this.dataLayoutControl1;
            this.ghichuTextEdit.TabIndex = 5;
            // 
            // emptySpaceItem1
            // 
            this.emptySpaceItem1.AllowHotTrack = false;
            this.emptySpaceItem1.Location = new System.Drawing.Point(161, 0);
            this.emptySpaceItem1.Name = "emptySpaceItem1";
            this.emptySpaceItem1.Size = new System.Drawing.Size(237, 24);
            this.emptySpaceItem1.TextSize = new System.Drawing.Size(0, 0);
            // 
            // f_themdmvean
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(418, 145);
            this.Controls.Add(this.dataLayoutControl1);
            this.Name = "f_themdmvean";
            this.Text = "Vé Ăn";
            this.Controls.SetChildIndex(this.dataLayoutControl1, 0);
            ((System.ComponentModel.ISupportInitialize)(this.dataLayoutControl1)).EndInit();
            this.dataLayoutControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.Root)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dmveanBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForidve)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForghichu)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.idveSpinEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ghichuTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private DevExpress.XtraDataLayout.DataLayoutControl dataLayoutControl1;
        private DevExpress.XtraLayout.LayoutControlGroup Root;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup1;
        private DevExpress.XtraEditors.SpinEdit idveSpinEdit;
        private System.Windows.Forms.BindingSource dmveanBindingSource;
        private DevExpress.XtraEditors.MemoEdit ghichuTextEdit;
        private DevExpress.XtraLayout.LayoutControlItem ItemForidve;
        private DevExpress.XtraLayout.LayoutControlItem ItemForghichu;
        private DevExpress.XtraLayout.EmptySpaceItem emptySpaceItem1;
    }
}