using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DAL;
using BUS;
using DevExpress.Utils.Win;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraEditors.Repository;
using DevExpress.XtraGrid.Columns;
using DevExpress.XtraGrid;
using System.Data.Linq;
using DevExpress.XtraReports.UI;
using ControlLocalizer;
using GUI.Properties;
namespace GUI
{
    public partial class f_baoco : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        KetNoiDBDataContext db = new KetNoiDBDataContext();
        t_pthu pthu = new t_pthu();
        t_cttk tk = new t_cttk();
        string manv = "";
        int checkmanv = 0;
        //form
        public f_baoco()
        {
            InitializeComponent();
            this.KeyPreview = true;
            var list = (from a in db.accounts select a).Single(t => t.id == Biencucbo.idnv);
            try
            {
                var list2 = (from a in db.doituongs select a).Single(t => t.manv == list.id);
                manv = list2.id;
                checkmanv = 1;
            }
            catch
            {
                checkmanv = 0;
            }
            lblbo.Text = "";
            lbltiente.Text = "";
            rsearchtiente1.DataSource = new DAL.KetNoiDBDataContext().tientes;
            txttiente.Properties.DataSource = new DAL.KetNoiDBDataContext().tientes;
            btnmuccp.DataSource = new DAL.KetNoiDBDataContext().muccps;
            btncongviec1.DataSource = new DAL.KetNoiDBDataContext().congviecs;
            var lst1 = from a in db.dmtks
                       where a.active == true
                       select new
                       {
                           matk = a.matk,
                           tentk = a.tentk,
                           matk_jp = a.matk_jp,
                           tentk_jp = a.tentk_jp,
                       };
            btntk.DataSource = lst1;
            var lst2 = from a in db.dmtks
                       where a.active == true && a.loaitk == "TIỀN GỬI NGÂN HÀNG"
                       select new
                       {
                           matk = a.matk,
                           tentk = a.tentk,
                           matk_jp = a.matk_jp,
                           tentk_jp = a.tentk_jp,
                           a.tiente,
                       };
            txttk.Properties.DataSource = lst2;
            txtiddt.Properties.DataSource = new DAL.KetNoiDBDataContext().doituongs;
            try
            {
                var lst = from a in db.hoadons
                          join b in db.hoadoncts on a.id equals b.idhoadon into g
                          join c in db.doituongs on a.iddt equals c.id
                          join d in db.donvis on a.iddv equals d.id
                          where Biencucbo.donvi == a.iddv || Biencucbo.donvi == d.iddv
                          select new
                          {
                              mahd = a.id,
                              ngayhd = a.ngayhd,
                              noidung = a.ghichu,
                              doituong = c.ten,
                              iddv = a.iddv,
                              tongtien = g.Sum(t => t.thanhtien)
                          };
                txtsohd.Properties.DataSource = lst;
            }
            catch
            {
            }
            // This line of code is generated by Data Source Configuration Wizard
            txtloaithu.Properties.DataSource = new DAL.KetNoiDBDataContext().dmloaithus;
            //tran
            //tran
            if (Biencucbo.ngonngu.ToString() == "Vietnam")
            {
                coldiengiai.Summary.AddRange(new DevExpress.XtraGrid.GridSummaryItem[] {
            new DevExpress.XtraGrid.GridColumnSummaryItem(DevExpress.Data.SummaryItemType.Sum, "diengiai", "Tổng cộng:")});
                gridColumn48.Summary.AddRange(new DevExpress.XtraGrid.GridSummaryItem[] {
            new DevExpress.XtraGrid.GridColumnSummaryItem(DevExpress.Data.SummaryItemType.Sum, "diengiai", "Tổng cộng:")});
                gridColumn85.Caption = "Danh mục";
                gridColumn86.Caption = "Danh mục";
                gridColumn35.Caption = "Mã Đối Tượng";
                gridColumn36.Caption = "Tên Đối Tượng ";
                gridColumn37.Caption = "Nhóm Đối Tượng";
                gridColumn38.Caption = "Loại Đối Tượng";
                gridColumn39.Caption = "Địa Chỉ";
                gridColumn82.Caption = "Tiền tệ";
                gridColumn83.Caption = "Tỷ giá";
                gridColumn84.Caption = "Ghi chú";
                gridColumn32.Caption = "Tiền tệ";
                gridColumn33.Caption = "Tỷ giá";
                gridColumn34.Caption = "Ghi chú";
                gridColumn59.Caption = "Mã Vạch";
                gridColumn60.Caption = "Tên Sản Phẩm";
                gridColumn61.Caption = "ĐVT";
                gridColumn43.Caption = "Mã công việc";
                gridColumn44.Caption = "Tên công việc";
                gridColumn46.Caption = "Nhóm công việc";
                gridColumn29.Caption = "Loại thuế";
                gridColumn30.Caption = "Tên thuế";
                gridColumn31.Caption = "Thuế suất";
                gridColumn41.Caption = "Mục Chi Phí";
                gridColumn42.Caption = "Tên Chi Phí";
                gridColumn27.Caption = "Số Hoá Đơn";
                gridColumn28.Caption = "Ngày Lập";
                gridColumn29.Caption = "Nội dung";
                gridColumn30.Caption = "Đối tượng";
                gridColumn31.Caption = "Tổng Tiền (KIP)";
                gridColumn47.Caption = "Mã Đơn Vị";
            }
            else //lao
            {
                coldiengiai.Summary.AddRange(new DevExpress.XtraGrid.GridSummaryItem[] {
            new DevExpress.XtraGrid.GridColumnSummaryItem(DevExpress.Data.SummaryItemType.Sum, "diengiai", "ລວມທັງໝົດ:")});
                gridColumn48.Summary.AddRange(new DevExpress.XtraGrid.GridSummaryItem[] {
            new DevExpress.XtraGrid.GridColumnSummaryItem(DevExpress.Data.SummaryItemType.Sum, "diengiai", "ລວມທັງໝົດ:")});
                gridColumn85.Caption = "ລາຍການ";
                gridColumn86.Caption = "ລາຍການ";
                gridColumn35.Caption = "ລະຫັດ";
                gridColumn36.Caption = "ຊື່ເປົ້າໝາຍ";
                gridColumn37.Caption = "ກຸ່ມເປົ້າໝາຍ";
                gridColumn38.Caption = "ປະເພດເປົ້າໝາຍ";
                gridColumn39.Caption = "ທີ່ຢູ່";
                gridColumn82.Caption = "ເງິນຕາ";
                gridColumn83.Caption = "ອັດຕາ";
                gridColumn84.Caption = "ໝາຍເຫດ";
                gridColumn32.Caption = "ເງິນຕາ";
                gridColumn33.Caption = "ອັດຕາ";
                gridColumn34.Caption = "ໝາຍເຫດ";
                gridColumn59.Caption = "ລະຫັດ";
                gridColumn60.Caption = "ຜະລິດຕະພັນ";
                gridColumn61.Caption = "ຫົວໜ່ວຍຄິດໄລ່";
                gridColumn43.Caption = "ລະຫັດວຽກງານ";
                gridColumn44.Caption = "ຊື່ວຽກງານ";
                gridColumn46.Caption = "ກຸ່ມໜ້າວຽກ";
                gridColumn29.Caption = "ປະເພດຂອງອາກອນ";
                gridColumn30.Caption = "ຊື່ອາກອນ";
                gridColumn31.Caption = "ອາກອນ (%)";
                gridColumn41.Caption = "ລາຍການຄ່າໃຊ້ຈ່າຍ";
                gridColumn42.Caption = "ຊື່ຄ່າໃຊ້ຈ່າຍ";
                gridColumn27.Caption = "ໃບບິນເລກທີ";
                gridColumn28.Caption = "ວັນທີ";
                gridColumn29.Caption = "ເນື້ອໃນ";
                gridColumn30.Caption = "ເປົ້າໝາຍ";
                gridColumn31.Caption = "ເປັນເງິນ (ກີບ)";
                gridColumn47.Caption = "ລະຫັດຫົວໜ່ວຍ";
            }
        }
        //load
        public void load()
        {
            //this.label1.BackColor = System.Drawing.Color.Transparent;
            db = new KetNoiDBDataContext();
            Biencucbo.hdpt = 2;
            txt1.Enabled = false;
            btnLuu.Enabled = false;
            btnsua.Enabled = true;
            btnxoa.Enabled = true;
            btnin.Enabled = true;
            btnreload.Enabled = false;
            txtdv.ReadOnly = true;
            txtid.ReadOnly = true;
            txtdiachi.ReadOnly = true;
            txtidnv.ReadOnly = true;
            txtphongban.ReadOnly = true;
            // Enable
            txtghichu.ReadOnly = true;
            txtngaynhap.ReadOnly = true;
            txtiddt.ReadOnly = true;
            txtsohd.ReadOnly = true;
            txtloaithu.ReadOnly = true;
            txttiente.ReadOnly = true;
            txttk.ReadOnly = true;
            txttygia.ReadOnly = true;
            gridView1.OptionsBehavior.Editable = false;
            try
            {
                var lst = (from a in db.pthus where a.iddv == Biencucbo.donvi && a.dv == "BC" select a.so).Max();
                var lst1 = (from b in db.pthus where b.iddv == Biencucbo.donvi && b.dv == "BC" select b).FirstOrDefault(t => t.so == lst);
                if (lst1 == null) return;
              
                txtid.Text = lst1.id;
                txtidnv.Text = lst1.idnv;
                txtdv.Text = lst1.iddv;
                txtngaynhap.DateTime = DateTime.Parse(lst1.ngaythu.ToString());
                txtiddt.Text = lst1.iddt;
                try
                {
                    var lst2 = (from a in db.doituongs select a).Single(t => t.id == txtiddt.Text);
                    lbltendt.Text = lst2.ten.ToString();
                    txtdiachi.Text = lst2.diachi.ToString();
                }
                catch (Exception)
                {
                }
                txttiente.Text = lst1.tiente;
                txttk.Text = lst1.tk;
                txttygia.Text = lst1.tygia.ToString();
                txtghichu.Text = lst1.ghichu;
                txttk.Text = lst1.tk;
                txtloaithu.Text = lst1.loaithu;
                txt1.Text = lst1.so.ToString();
                txtsohd.Text = lst1.link;
                gcchitiet.DataSource = lst1.pthucts;
            }
            catch
            {
            }
        }
        // phân quyền 
        protected override void OnActivated(EventArgs e)
        {
            base.OnActivated(e);
            var q = Biencucbo.QuyenDangChon;
            if (q == null) return;
            if ((bool)q.Them == true)
            {
                btnnew.Visibility = DevExpress.XtraBars.BarItemVisibility.Always;
            }
            else
            {
                btnnew.Visibility = DevExpress.XtraBars.BarItemVisibility.Never;
            }
            if ((bool)q.Sua == true)
            {
                btnsua.Visibility = DevExpress.XtraBars.BarItemVisibility.Always;
            }
            else
            {
                btnsua.Visibility = DevExpress.XtraBars.BarItemVisibility.Never;
            }
            if ((bool)q.Xoa == true)
            {
                btnxoa.Visibility = DevExpress.XtraBars.BarItemVisibility.Always;
            }
            else
            {
                btnxoa.Visibility = DevExpress.XtraBars.BarItemVisibility.Never;
            }
        }
        // Mở
        private void btnmo_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Biencucbo.ltlc = 2;
            db = new KetNoiDBDataContext();
            f_dspthu frm = new f_dspthu();
            frm.ShowDialog();
            if (Biencucbo.getID == 1)
            {
                //load pnhap
                try
                {
                    var lst = (from pn in db.pthus select new { a = pn }).FirstOrDefault(x => x.a.id == Biencucbo.ma);
                    if (lst == null) return;
                    txtid.Text = lst.a.id;
                    txtidnv.Text = lst.a.idnv;
                    txtdv.Text = lst.a.iddv;
                    txtngaynhap.DateTime = DateTime.Parse(lst.a.ngaythu.ToString());
                    txtiddt.Text = lst.a.iddt;
                    txtghichu.Text = lst.a.ghichu;
                    txt1.Text = lst.a.so.ToString();
                    txttiente.Text = lst.a.tiente;
                    txttk.Text = lst.a.tk;
                    txttygia.Text = lst.a.tygia.ToString();
                    txtsohd.Text = lst.a.link;
                    txttk.Text = lst.a.tk;
                    txtloaithu.Text = lst.a.loaithu;
                    gcchitiet.DataSource = lst.a.pthucts;
                    //btn
                    btnnew.Enabled = true;
                    btnsua.Enabled = true;
                    btnLuu.Enabled = false;
                    btnmo.Enabled = true;
                    btnxoa.Enabled = true;
                    btnin.Enabled = true;
                    btnreload.Enabled = false;
                }
                catch
                {
                }
            }
        }
        //Thêm
        private void btnnew_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Biencucbo.hdpt = 0;
            txtid.DataBindings.Clear();
            txtid.Text = "YYYYY";
            gcchitiet.DataSource = new DAL.KetNoiDBDataContext().View_pthus;
            for (int i = 0; i <= gridView1.RowCount - 1; i++)
            {
                gridView1.DeleteRow(i);
            }
            gridView1.AddNewRow();
            txtdv.Text = Biencucbo.donvi;
            txtngaynhap.DateTime = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day);
            txtphongban.Text = Biencucbo.phongban;
            txtidnv.Text = Biencucbo.idnv.Trim();
            lbltennv.Text = Biencucbo.ten;
            txtngaynhap.Focus();
            txtiddt.Text = "";
            lbltendt.Text = "";
            txtsohd.Text = "";
            txtghichu.Text = "";
            txttiente.Text = "KIP";
            txttk.Text = "111";
            txttygia.Text = "1";
            //btn
            btnnew.Enabled = false;
            btnmo.Enabled = false;
            btnLuu.Enabled = true;
            btnsua.Enabled = false;
            btnxoa.Enabled = false;
            btnin.Enabled = false;
            btnreload.Enabled = false;
            //enabled
            txtghichu.ReadOnly = false;
            txtngaynhap.ReadOnly = false;
            txtiddt.ReadOnly = false;
            txtsohd.ReadOnly = false;
            txtloaithu.ReadOnly = false;
            txttiente.ReadOnly = true;
            txttk.ReadOnly = false;
            txttygia.ReadOnly = true;
            gridView1.OptionsBehavior.Editable = true;
        }
        //Lưu
        public void luu()
        {
            t_history hs = new t_history();
            t_tudong td = new t_tudong();
            gridView1.UpdateCurrentRow();
            if (txtngaynhap.Text == "" || txtiddt.Text == "" || txttiente.Text == "" || txttygia.Text == "" || txtloaithu.Text == "" || txttk.Text == "")
            {
                Lotus.MsgBox.ShowWarningDialog("Thông tin chưa đầy đủ - Vui lòng kiểm tra lại!");
            }
            else
            {
                if (Biencucbo.hdpt == 0)
                {
                    db = new KetNoiDBDataContext();
                    try
                    {
                        string check = "BC" + Biencucbo.donvi.Trim().ToString();
                        var lst1 = (from s in db.tudongs where s.maphieu == check select new { so = s.so }).ToList();
                        if (lst1.Count == 0)
                        {
                            int so;
                            so = 2;
                            td.themtudong(check, so, "BC" , "Phiếu Báo Có");
                            txtid.Text = check + "_000001";
                            txt1.Text = "1";
                        }
                        else
                        {
                            int k;
                            txt1.DataBindings.Clear();
                            txt1.DataBindings.Add("text", lst1, "so");
                            k = 0;
                            k = Convert.ToInt32(txt1.Text);
                            string so0 = "";
                            if (k < 10)
                            {
                                so0 = "00000";
                            }
                            else if (k >= 10 & k < 100)
                            {
                                so0 = "0000";
                            }
                            else if (k >= 100 & k < 1000)
                            {
                                so0 = "000";
                            }
                            else if (k >= 1000 & k < 10000)
                            {
                                so0 = "00";
                            }
                            else if (k >= 10000 & k < 100000)
                            {
                                so0 = "0";
                            }
                            else if (k >= 100000)
                            {
                                so0 = "";
                            }
                            txtid.Text = check + "_" + so0 + k;
                            k = k + 1;
                            td.suatudong(check, k);
                        }
                        pthu.moipthu(txtid.Text, txtngaynhap.DateTime, txtiddt.Text, txtdv.Text, txtidnv.Text, txtghichu.Text, Convert.ToInt32(txt1.Text), txtsohd.Text, txttiente.Text, double.Parse(txttygia.Text), txtloaithu.Text, txttk.Text, "BC");
                        for (int i = 0; i <= gridView1.RowCount - 1; i++)
                        {
                            gridView1.SetRowCellValue(i, "idthu", txtid.Text);
                            gridView1.SetRowCellValue(i, "id", txtid.Text + i);
                            pthu.moict(gridView1.GetRowCellValue(i, "diengiai").ToString(), gridView1.GetRowCellValue(i, "idcv").ToString(), gridView1.GetRowCellValue(i, "idmuccp").ToString(), double.Parse(gridView1.GetRowCellValue(i, "thanhtien").ToString()), gridView1.GetRowCellValue(i, "idthu").ToString(), gridView1.GetRowCellValue(i, "id").ToString(), gridView1.GetRowCellValue(i, "tiente").ToString(), double.Parse(gridView1.GetRowCellValue(i, "tygia").ToString()), double.Parse(gridView1.GetRowCellValue(i, "nguyente").ToString()), gridView1.GetRowCellValue(i, "tkco").ToString());
                            tk.moi(txtid.Text + i + "1", txtdv.Text, "BC", txtid.Text, txtngaynhap.DateTime, new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day), Convert.ToInt32(txt1.Text), Biencucbo.donvi, txtiddt.Text, gridView1.GetRowCellValue(i, "diengiai").ToString(), txttk.Text, gridView1.GetRowCellValue(i, "tkco").ToString(), double.Parse(gridView1.GetRowCellValue(i, "thanhtien").ToString()), txttiente.Text, double.Parse(txttygia.Text), double.Parse(gridView1.GetRowCellValue(i, "nguyente").ToString()), "", "", txtidnv.Text, txtloaithu.Text, gridView1.GetRowCellValue(i, "idcv").ToString(), "", lbltendt.Text, txtghichu.Text, 0.0);
                        }
                        //btn
                        btnmo.Enabled = true;
                        btnnew.Enabled = true;
                        btnLuu.Enabled = false;
                        btnsua.Enabled = true;
                        btnxoa.Enabled = true;
                        btnin.Enabled = true;
                        btnreload.Enabled = false;
                        //enabled
                        txtghichu.ReadOnly = true;
                        txtngaynhap.ReadOnly = true;
                        txtiddt.ReadOnly = true;
                        txtsohd.ReadOnly = true;
                        txtloaithu.ReadOnly = true;
                        txttiente.ReadOnly = true;
                        txttk.ReadOnly = true;
                        txttygia.ReadOnly = true;
                        gridView1.OptionsBehavior.Editable = false;
                        Biencucbo.hdpt = 2;
                        // History
                        hs.add(txtid.Text, "Thêm mới chứng từ");
                    }
                    catch (Exception ex)
                    {
                        XtraMessageBox.Show(ex.Message);
                    }
                }
                else
                {
                    try
                    {
                        pthu.suapt(txtid.Text, DateTime.Parse(txtngaynhap.Text), txtiddt.Text, txtghichu.Text, int.Parse(txt1.Text), txtsohd.Text, txttiente.Text, double.Parse(txttygia.Text), txtloaithu.Text, txttk.Text);
                        //sua ct
                        LuuPhieu();
                        tk.xoa(txtid.Text);
                        for (int i = 0; i <= gridView1.RowCount - 1; i++)
                        {
                            tk.moi(txtid.Text + i + "1", txtdv.Text, "BC", txtid.Text, txtngaynhap.DateTime, new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day), Convert.ToInt32(txt1.Text), Biencucbo.donvi, txtiddt.Text, gridView1.GetRowCellValue(i, "diengiai").ToString(), txttk.Text, gridView1.GetRowCellValue(i, "tkco").ToString(), double.Parse(gridView1.GetRowCellValue(i, "thanhtien").ToString()), txttiente.Text, double.Parse(txttygia.Text), double.Parse(gridView1.GetRowCellValue(i, "nguyente").ToString()), "", "", txtidnv.Text, txtloaithu.Text, gridView1.GetRowCellValue(i, "idcv").ToString(), "", lbltendt.Text, txtghichu.Text, 0.0);
                        }
                        //btn
                        btnmo.Enabled = true;
                        btnnew.Enabled = true;
                        btnLuu.Enabled = false;
                        btnsua.Enabled = true;
                        btnxoa.Enabled = true;
                        btnin.Enabled = true;
                        btnreload.Enabled = false;
                        //enabled
                        txtghichu.ReadOnly = true;
                        txtngaynhap.ReadOnly = true;
                        txtiddt.ReadOnly = true;
                        txtsohd.ReadOnly = true;
                        txtloaithu.ReadOnly = true;
                        txttiente.ReadOnly = true;
                        txttk.ReadOnly = true;
                        txttygia.ReadOnly = true;
                        gridView1.OptionsBehavior.Editable = false;
                        Biencucbo.hdpt = 2;
                        hs.add(txtid.Text, "Sửa chứng từ");
                    }
                    catch (Exception ex)
                    {
                        XtraMessageBox.Show(ex.ToString());
                    }
                }
            }
        }
        private void btnLuu_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            gridView1.PostEditor();
            gridView1.UpdateCurrentRow();
            for (int i = 0; i <= gridView1.RowCount - 1; i++)
            {
                if (gridView1.GetRowCellDisplayText(i, "tkco").ToString() == "")
                {
                    Lotus.MsgBox.ShowWarningDialog("Thông tin chưa đầy đủ - Vui lòng kiểm tra lại!");
                    return;
                }
            }
            if (checkmanv == 0)
            {
                Lotus.MsgBox.ShowWarningDialog("Nhân viên này chưa được tạo mã đối tượng - Vui lòng kiểm tra lại!");
                return;
            }
            var lst = (from a in db.doituongs where a.id == Biencucbo.donvi select a);
            if (lst.Count() == 0)
            {
                MessageBox.Show("Đơn vị này chưa được tạo đối tượng - Vui lòng kiểm tra lại hoặc liên hệ Admin!", "THÔNG BÁO");
                return;
            }
            luu();
        }
        bool LuuPhieu()
        {
            // kiem tra truoc khi luu
            layoutControl1.Validate();
            gridView1.CloseEditor();
            gridView1.UpdateCurrentRow();
            // if(kiem tra rang buoc)
            //  return false;
            try
            {
                var c1 = db.pthus.Context.GetChangeSet();
                /* db.pnhaps.Context.SubmitChanges(); */// dang báo lỗi là vi không có thay đổi. kiem tra neu có thay doi hãy submit
                db.pthucts.Context.SubmitChanges();
            }
            catch (Exception ex)
            {
                XtraMessageBox.Show(ex.Message);
                return false;
            }
            return true;
        }
        //Sửa
        private void btnsua_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (txtid.Text == "")
            {
                return;
            }
            //load 
            try
            {
                var lst = (from pn in db.pthus select pn).FirstOrDefault(x => x.id == txtid.Text);
                if (lst == null) return;
                gcchitiet.DataSource = lst.pthucts;
                //enabled
                txtghichu.ReadOnly = false;
                txtngaynhap.ReadOnly = false;
                txtiddt.ReadOnly = false;
                txtsohd.ReadOnly = false;
                txtloaithu.ReadOnly = false;
                txttiente.ReadOnly = true;
                txttk.ReadOnly = false;
                txttygia.ReadOnly = true;
                gridView1.OptionsBehavior.Editable = true;
                Biencucbo.hdpt = 1;
                // btn
                btnsua.Enabled = false;
                btnLuu.Enabled = true;
                btnmo.Enabled = false;
                btnnew.Enabled = false;
                btnxoa.Enabled = false;
                btnin.Enabled = false;
                btnreload.Enabled = true;
            }
            catch
            {
            }
        }
        //Xóa
        private void btnxoa_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (txtid.Text == "")
            {
                return;
            }
            if (XtraMessageBox.Show("Bạn có chắc chắn muốn xóa Phiếu " + txtid.Text + " không?", "THÔNG BÁO", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
            {
                t_history hs = new t_history();
                hs.add(txtid.Text, "Xóa chứng từ");
                try
                {
                    tk.xoa(txtid.Text);
                    for (int i = gridView1.DataRowCount - 1; i >= 0; i--)
                    {
                        pthu.xoact(gridView1.GetRowCellValue(i, "id").ToString());
                        gridView1.DeleteRow(i);
                    }
                    pthu.xoapthu(txtid.Text);
                    //btn
                    btnmo.Enabled = true;
                    btnnew.Enabled = true;
                    btnLuu.Enabled = false;
                    btnsua.Enabled = true;
                    btnxoa.Enabled = true;
                    btnin.Enabled = true;
                    btnreload.Enabled = false;
                    //enabled
                    txtghichu.ReadOnly = true;
                    txtngaynhap.ReadOnly = true;
                    txtiddt.ReadOnly = true;
                    txtsohd.ReadOnly = true;
                    txtloaithu.ReadOnly = true;
                    txttiente.ReadOnly = true;
                    txttk.ReadOnly = true;
                    txttygia.ReadOnly = true;
                    gridView1.OptionsBehavior.Editable = false;
                    //gcchitiet.DataSource = new DAL.KetNoiDBDataContext().View_pnhapcts;
                    txtdv.Text = "";
                    txtid.Text = "";
                    txtidnv.Text = "";
                    txtdv.Text = "";
                    txtngaynhap.Text = "";
                    txtiddt.Text = "";
                    txtghichu.Text = "";
                    txt1.Text = "";
                    txtsohd.Text = "";
                    lbltendt.Text = "";
                    lbltennv.Text = "";
                    txttiente.Text = "";
                    txttk.Text = "";
                    txttygia.Text = "";
                }
                catch
                {
                }
            }
        }
        //In
        private void btnin_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
        }
        //reload
        private void btnload_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (Biencucbo.hdpt == 1)
            {
                db = new KetNoiDBDataContext();
                var lst = (from pn in db.pthus select pn).FirstOrDefault(x => x.id == txtid.Text);
                if (lst == null) return;
                txtidnv.Text = lst.idnv;
                txtdv.Text = lst.iddv;
                txtngaynhap.DateTime = DateTime.Parse(lst.ngaythu.ToString());
                txtiddt.Text = lst.iddt;
                txtghichu.Text = lst.ghichu;
                txt1.Text = lst.so.ToString();
                txtsohd.Text = lst.link;
                txttk.Text = lst.tk;
                txttiente.Text = lst.tiente;
                txttk.Text = lst.tk;
                txttygia.Text = lst.tygia.ToString();
                gcchitiet.DataSource = lst.pthucts;
                txtloaithu.Text = lst.loaithu;
                //readonly
                txtghichu.ReadOnly = true;
                txtngaynhap.ReadOnly = true;
                txttiente.ReadOnly = true;
                txttk.ReadOnly = true;
                txttygia.ReadOnly = true;
                txtiddt.ReadOnly = true;
                txtsohd.ReadOnly = true;
                txtloaithu.ReadOnly = true;
                //btn
                btnnew.Enabled = true;
                btnsua.Enabled = true;
                btnLuu.Enabled = false;
                btnmo.Enabled = true;
                btnxoa.Enabled = true;
                btnin.Enabled = true;
                btnreload.Enabled = false;
                gridView1.OptionsBehavior.Editable = false;
            }
            else if (Biencucbo.hdpt == 0)
            {
                load();
                btnnew.Enabled = true;
                btnsua.Enabled = true;
                btnLuu.Enabled = false;
                btnmo.Enabled = true;
                btnxoa.Enabled = true;
                btnin.Enabled = true;
                btnreload.Enabled = false;
                gridView1.OptionsBehavior.Editable = false;
            }
            Biencucbo.hdpt = 2;
        }
        // thay đổi
        private void gridView1_CellValueChanged(object sender, DevExpress.XtraGrid.Views.Base.CellValueChangedEventArgs e)
        {
            gridView1.PostEditor();
            if (e.Column.FieldName == "nguyente")
            {
                try
                {
                    gridView1.SetFocusedRowCellValue("thanhtien", (double.Parse(gridView1.GetFocusedRowCellValue("nguyente").ToString())) * (double.Parse(txttygia.Text)));
                }
                catch (Exception)
                {
                }
            }
        }
        //Phím Tắt
        private void gridView1_KeyDown(object sender, KeyEventArgs e)
        {
            if (Biencucbo.hdpt != 2)
            {
                if (e.KeyCode == Keys.Insert)
                {
                    gridView1.AddNewRow();
                }
                else if (e.KeyCode == Keys.Delete)
                {
                    gridView1.DeleteRow(gridView1.FocusedRowHandle);
                }
            }
            else
            {
                if (e.KeyCode == Keys.F4)
                {
                    Biencucbo.ma = txtid.Text;
                    f_dinhkhoan frm = new f_dinhkhoan();
                    frm.ShowDialog();
                }
            }
        }
        //đối tượng
        private void txtiddt_EditValueChanged(object sender, EventArgs e)
        {
            try
            {
                var lst = (from a in db.doituongs select a).Single(t => t.id == txtiddt.Text);
                lbltendt.Text = lst.ten.ToString();
                txtdiachi.Text = lst.diachi.ToString();
            }
            catch (Exception)
            {
            }
        }
        //Dòng mới
        private void gridView1_InitNewRow(object sender, InitNewRowEventArgs e)
        {
            if (Biencucbo.hdpt == 1)
            {
                var ct = gridView1.GetFocusedRow() as pthuct;
                if (ct == null) return;
                int i = 0, k = 0;
                string a;
                k = gridView1.DataRowCount;
                a = txtid.Text + k;
                for (i = 0; i <= gridView1.DataRowCount - 1;)
                {
                    if (a == gridView1.GetRowCellValue(i, "id").ToString())
                    {
                        k = k + 1;
                        a = txtid.Text + k;
                        i = 0;
                    }
                    else
                    {
                        i++;
                    }
                }
                ct.idthu = txtid.Text;
                ct.diengiai = "";
                ct.idmuccp = "";
                ct.idcv = "";
                ct.thanhtien = 0;
                ct.id = a;
                ct.tiente = "KIP";
                ct.tygia = 1;
                ct.nguyente = 0;
            }
            else
            {
                gridView1.SetFocusedRowCellValue("diengiai", "");
                gridView1.SetFocusedRowCellValue("tygia", 1);
                gridView1.SetFocusedRowCellValue("idmuccp", "");
                gridView1.SetFocusedRowCellValue("tiente", "KIP");
                gridView1.SetFocusedRowCellValue("idcv", "");
                gridView1.SetFocusedRowCellValue("nguyente", 0);
            }
        }
        //Xóa dòng
        private void btnin_ItemClick_1(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                var lst = (from a in db.r_pthus where a.id == txtid.Text select a);
                for (int i = 0; i < gridView1.DataRowCount; i++)
                {
                    if (i == 0)
                    {
                        Biencucbo.tkco = gridView1.GetRowCellValue(i, "tkco").ToString();
                    }
                    else
                    {
                        Biencucbo.tkco = Biencucbo.tkco + "-" + gridView1.GetRowCellValue(i, "tkco").ToString();
                    }
                }
                Biencucbo.tientebc = txttiente.Text;
                Biencucbo.tygiabc = txttygia.Text;
                Biencucbo.tkno = txttk.Text;
                Biencucbo.ngaynhap = txtngaynhap.DateTime;
                Biencucbo.diachi = txtdiachi.Text;
                r_pthu xtra = new r_pthu();
                xtra.DataSource = lst;
                xtra.ShowPreviewDialog();
            }
            catch
            {
            }
        }
        //đóng form
        private void f_pnhap_FormClosing(object sender, FormClosingEventArgs e)
        {
            if (Biencucbo.hdpt != 2)
            {
                var a = Lotus.MsgBox.ShowYesNoCancelDialog("Phiếu này chưa được lưu - Bạn có muốn lưu Phiếu này trước khi thoát không?");
                if (a == DialogResult.Yes)
                {
                    luu();
                }
                else if (a == DialogResult.Cancel) e.Cancel = true;
            }
        }
        private void gridView1_CustomDrawRowIndicator(object sender, RowIndicatorCustomDrawEventArgs e)
        {
            if (!gridView1.IsGroupRow(e.RowHandle)) //Nếu không phải là Group
            {
                if (e.Info.IsRowIndicator) //Nếu là dòng Indicator
                {
                    if (e.RowHandle < 0)
                    {
                        e.Info.ImageIndex = 0;
                        e.Info.DisplayText = string.Empty;
                    }
                    else
                    {
                        e.Info.ImageIndex = -1; //Không hiển thị hình
                        e.Info.DisplayText = (e.RowHandle + 1).ToString(); //Số thứ tự tăng dần
                    }
                    SizeF _Size = e.Graphics.MeasureString(e.Info.DisplayText, e.Appearance.Font); //Lấy kích thước của vùng hiển thị Text
                    Int32 _Width = Convert.ToInt32(_Size.Width) + 20;
                    BeginInvoke(new MethodInvoker(delegate { cal(_Width, gridView1); })); //Tăng kích thước nếu Text vượt quá
                }
            }
            else
            {
                e.Info.ImageIndex = -1;
                e.Info.DisplayText = string.Format("[{0}]", (e.RowHandle * -1)); //Nhân -1 để đánh lại số thứ tự tăng dần
                SizeF _Size = e.Graphics.MeasureString(e.Info.DisplayText, e.Appearance.Font);
                Int32 _Width = Convert.ToInt32(_Size.Width) + 20;
                BeginInvoke(new MethodInvoker(delegate { cal(_Width, gridView1); }));
            }
        }
        bool cal(Int32 _Width, GridView _View)
        {
            _View.IndicatorWidth = _View.IndicatorWidth < _Width ? _Width : _View.IndicatorWidth;
            return true;
        }
        private void btnmuccp_EditValueChanged(object sender, EventArgs e)
        {
            gridView1.PostEditor();
        }
        private void rsearchtiente1_EditValueChanged(object sender, EventArgs e)
        {
            try
            {
                gridView1.PostEditor();
                var lst = (from a in db.tientes select a).Single(t => t.tiente1 == gridView1.GetFocusedRowCellValue("tiente").ToString());
                if (lst == null) return;
                gridView1.SetFocusedRowCellValue("tygia", lst.tygia);
                gridView1.SetFocusedRowCellValue("thanhtien", int.Parse(gridView1.GetFocusedRowCellValue("nguyente").ToString()) * int.Parse(gridView1.GetFocusedRowCellValue("tygia").ToString()));
            }
            catch
            {
            }
        }
        private void f_pthu_Load(object sender, EventArgs e)
        {
            LanguageHelper.Translate(this);
            LanguageHelper.Translate(barManager1);
            this.Text = LanguageHelper.TranslateMsgString("." + Name + "_title", "Báo có").ToString();
            changeFont.Translate(this);
            changeFont.Translate(barManager1);
            load();
        }
        private void txttiente_EditValueChanged(object sender, EventArgs e)
        {
            try
            {
                var lst = (from a in new DAL.KetNoiDBDataContext().tientes select a).FirstOrDefault(t => t.tiente1 == txttiente.Text);
                txttygia.Text = lst.tygia.ToString();
                for (int i = 0; i <= gridView1.RowCount - 1; i++)
                {
                    try
                    {
                        gridView1.SetRowCellValue(i, "thanhtien", double.Parse(gridView1.GetRowCellValue(i, "nguyente").ToString()) * double.Parse(txttygia.Text));
                    }
                    catch
                    {
                    }
                }
            }
            catch
            {
            }
        }
        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
        }
        private void txttk_EditValueChanged(object sender, EventArgs e)
        {
            try
            {
                var lst = (from a in db.dmtks select a).Single(t => t.matk == txttk.Text);
                lbtk.Text = lst.tentk;
                txttiente.Text = lst.tiente;
            }
            catch
            {
                lbtk.Text = "";
                txttiente.Text = "KIP";
            }
        }
        private void txtiddt_Popup(object sender, EventArgs e)
        {
            IPopupControl popupControl = sender as IPopupControl;
            SimpleButton button = new SimpleButton()
            {
                Image = Resources.icons8_Add_File_16,
                Text = "Thêm mới",
                BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder
            };
            button.Click += new EventHandler(button_Click);
            button.Location = new Point(5, popupControl.PopupWindow.Height - button.Height - 5);
            popupControl.PopupWindow.Controls.Add(button);
            button.BringToFront();
        }
        public void button_Click(object sender, EventArgs e)
        {
            f_doituong frm = new f_doituong();
            frm.ShowDialog();
            txtiddt.Properties.DataSource = new DAL.KetNoiDBDataContext().doituongs;
        }
        private void txtidnv_EditValueChanged(object sender, EventArgs e)
        {
            var lst = (from a in db.accounts select a).Single(t => t.id == txtidnv.Text);
            lbltennv.Text = lst.name;
            txtphongban.Text = lst.phongban;
        }
        private void f_baoco_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.Control && e.KeyCode == Keys.P)
            {
                try
                {
                    var lst = (from a in db.r_pthus where a.id == txtid.Text select a);
                    for (int i = 0; i < gridView1.DataRowCount; i++)
                    {
                        if (i == 0)
                        {
                            Biencucbo.tkco = gridView1.GetRowCellValue(i, "tkco").ToString();
                        }
                        else
                        {
                            Biencucbo.tkco = Biencucbo.tkco + "-" + gridView1.GetRowCellValue(i, "tkco").ToString();
                        }
                    }
                    Biencucbo.tkno = txttk.Text;
                    Biencucbo.diachi = txtdiachi.Text;
                    r_pthu xtra = new r_pthu();
                    xtra.DataSource = lst;
                    xtra.ShowPreviewDialog();
                }
                catch
                {
                }
            }
        }
        private void txttiente_Popup(object sender, EventArgs e)
        {
        }
        private void txttiente_Click(object sender, EventArgs e)
        {
        }
        private void btnnext_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            // next	
            if (Biencucbo.hdpt != 2)
                return;
            try
            {
                var so = (from pn in db.pthus where pn.iddv == txtdv.Text && pn.so > int.Parse(txt1.Text) select pn.so).Min();
                var lst1 = (from pn in db.pthus where pn.iddv == txtdv.Text select pn).FirstOrDefault(x => x.so == so);
                if (lst1 == null) return;
                gcchitiet.DataSource = lst1.pthucts;
                txtid.Text = lst1.id;
                txtidnv.Text = lst1.idnv;
                txtdv.Text = lst1.iddv;
                txtngaynhap.DateTime = DateTime.Parse(lst1.ngaythu.ToString());
                txtiddt.Text = lst1.iddt;
                try
                {
                    var lst2 = (from a in db.doituongs select a).Single(t => t.id == txtiddt.Text);
                    lbltendt.Text = lst2.ten.ToString();
                    txtdiachi.Text = lst2.diachi.ToString();
                }
                catch (Exception)
                {
                }
                txttiente.Text = lst1.tiente;
                txttk.Text = lst1.tk;
                txttygia.Text = lst1.tygia.ToString();
                txtghichu.Text = lst1.ghichu;
                txttk.Text = lst1.tk;
                txtloaithu.Text = lst1.loaithu;
                txt1.Text = lst1.so.ToString();
                txtsohd.Text = lst1.link;
            }
            catch
            {
            }
        }
        private void btnpre_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //previous
            if (Biencucbo.hdpt != 2)
                return;
            try
            {
                var so = (from pn in db.pthus where pn.iddv == txtdv.Text && pn.so < int.Parse(txt1.Text) select pn.so).Max();
                var lst1 = (from pn in db.pthus where pn.iddv == txtdv.Text select pn).FirstOrDefault(x => x.so == so);
                if (lst1 == null) return;
                gcchitiet.DataSource = lst1.pthucts;
                txtid.Text = lst1.id;
                txtidnv.Text = lst1.idnv;
                txtdv.Text = lst1.iddv;
                txtngaynhap.DateTime = DateTime.Parse(lst1.ngaythu.ToString());
                txtiddt.Text = lst1.iddt;
                try
                {
                    var lst2 = (from a in db.doituongs select a).Single(t => t.id == txtiddt.Text);
                    lbltendt.Text = lst2.ten.ToString();
                    txtdiachi.Text = lst2.diachi.ToString();
                }
                catch (Exception)
                {
                }
                txttiente.Text = lst1.tiente;
                txttk.Text = lst1.tk;
                txttygia.Text = lst1.tygia.ToString();
                txtghichu.Text = lst1.ghichu;
                txttk.Text = lst1.tk;
                txtloaithu.Text = lst1.loaithu;
                txt1.Text = lst1.so.ToString();
                txtsohd.Text = lst1.link;
            }
            catch
            {
            }
        }
        private void btnlast_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (Biencucbo.hdpt != 2)
                return;
            try
            {
                var lsta = (from a in db.pthus where a.iddv == txtdv.Text select a).Max(t => t.so);
                var lst1 = (from pn in db.pthus where pn.iddv == txtdv.Text select pn).FirstOrDefault(x => x.so == lsta);
                if (lst1 == null) return;
                gcchitiet.DataSource = lst1.pthucts;
                txtid.Text = lst1.id;
                txtidnv.Text = lst1.idnv;
                txtdv.Text = lst1.iddv;
                txtngaynhap.DateTime = DateTime.Parse(lst1.ngaythu.ToString());
                txtiddt.Text = lst1.iddt;
                try
                {
                    var lst2 = (from a in db.doituongs select a).Single(t => t.id == txtiddt.Text);
                    lbltendt.Text = lst2.ten.ToString();
                    txtdiachi.Text = lst2.diachi.ToString();
                }
                catch (Exception)
                {
                }
                txttiente.Text = lst1.tiente;
                txttk.Text = lst1.tk;
                txttygia.Text = lst1.tygia.ToString();
                txtghichu.Text = lst1.ghichu;
                txttk.Text = lst1.tk;
                txtloaithu.Text = lst1.loaithu;
                txt1.Text = lst1.so.ToString();
                txtsohd.Text = lst1.link;
            }
            catch
            {
            }
        }
        private void btnfirst_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (Biencucbo.hdpt != 2)
                return;
            try
            {
                var lsta = (from a in db.pthus where a.iddv == txtdv.Text select a).Min(t => t.so);
                var lst1 = (from pn in db.pthus where pn.iddv == txtdv.Text select pn).FirstOrDefault(x => x.so == lsta);
                if (lst1 == null) return;
                gcchitiet.DataSource = lst1.pthucts;
                txtid.Text = lst1.id;
                txtidnv.Text = lst1.idnv;
                txtdv.Text = lst1.iddv;
                txtngaynhap.DateTime = DateTime.Parse(lst1.ngaythu.ToString());
                txtiddt.Text = lst1.iddt;
                try
                {
                    var lst2 = (from a in db.doituongs select a).Single(t => t.id == txtiddt.Text);
                    lbltendt.Text = lst2.ten.ToString();
                    txtdiachi.Text = lst2.diachi.ToString();
                }
                catch (Exception)
                {
                }
                txttiente.Text = lst1.tiente;
                txttk.Text = lst1.tk;
                txttygia.Text = lst1.tygia.ToString();
                txtghichu.Text = lst1.ghichu;
                txttk.Text = lst1.tk;
                txtloaithu.Text = lst1.loaithu;
                txt1.Text = lst1.so.ToString();
                txtsohd.Text = lst1.link;
            }
            catch
            {
            }
        }
        private void gridView1_RowDeleting(object sender, DevExpress.Data.RowDeletingEventArgs e)
        {
            if (Biencucbo.hdpt == 1)
            {
                try
                {
                    pthuct ct = (from c in db.pthucts select c).Single(x => x.id == gridView1.GetFocusedRowCellValue("id").ToString());
                    db.pthucts.DeleteOnSubmit(ct);
                }
                catch
                {
                }
            }
        }
        private void btntygia_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            f_tiente2 frm = new f_tiente2();
            frm.ShowDialog();
        }
    }
}
