using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DAL;
using BUS;
using DevExpress.XtraEditors;
using System.Data.Linq;
using DevExpress.XtraReports.UI;
using ControlLocalizer;
using DevExpress.Utils.Win;
using GUI.Properties;
namespace GUI
{
    public partial class f_pxuatbh_fifo : Form
    {
        KetNoiDBDataContext db = new KetNoiDBDataContext();
        t_hoadon hd = new t_hoadon();
        t_cttk tk = new t_cttk();
        t_tonsp ton = new t_tonsp();
        double mua = 0;
        double ban = 0;
        double soluong3 = 0;
        string madv = "";
        int checkmadv = 0;
        string masp = "";
        int checkmasp = 0;
        public f_pxuatbh_fifo()
        {
            InitializeComponent();
            // tinh so luong ton san pham
            try
            {
                var lst = (from a in db.r_giasps where a.iddv == Biencucbo.donvi select new { id = a.idsp, tensp = a.tensp, dvt = a.dvt });
                if (lst == null) return;
                btnmasp.DataSource = lst;
                rsearchTenSP.DataSource = btnmasp.DataSource;
                btndvt.DataSource = btnmasp.DataSource;
            }
            catch
            {
            }
            rsearchtiente.DataSource = new DAL.KetNoiDBDataContext().tientes;
            txtbanhang.Enabled = false;
            txttiente.Properties.DataSource = new DAL.KetNoiDBDataContext().tientes;
            btnthue.DataSource = new DAL.KetNoiDBDataContext().thues;
            rsearchthuesuat.DataSource = btnthue.DataSource;
            btncongviec.DataSource = new DAL.KetNoiDBDataContext().congviecs;
            txtiddt.Properties.DataSource = new DAL.KetNoiDBDataContext().doituongs;
            // This line of code is generated by Data Source Configuration Wizard
            // This line of code is generated by Data Source Configuration Wizard
            txtloaihd.Properties.DataSource = new DAL.KetNoiDBDataContext().dmxuatkhos;
            try
            {
                var list2 = (from a in db.doituongs select a).Single(t => t.madv == Biencucbo.donvi);
                madv = list2.id;
                checkmadv = 1;
            }
            catch
            {
                checkmadv = 0;
            }
            try
            {
                var lst = from a in db.banhangs
                          join b in db.banhangcts on a.id equals b.idbanhang into g
                          join c in db.doituongs on a.iddt equals c.id
                          join d in db.donvis on a.iddv equals d.id
                          where Biencucbo.donvi == a.iddv || Biencucbo.donvi == d.iddv
                          select new
                          {
                              id = a.id,
                              ngayhd = a.ngayban,
                              noidung = a.ghichu,
                              doituong = c.ten,
                              iddv = a.iddv,
                              tongtien = g.Sum(t => t.thanhtien)
                          };
                txtbanhang.Properties.DataSource = lst;
            }
            catch
            {
            }
        }
        // phân quyền 
        protected override void OnActivated(EventArgs e)
        {
            base.OnActivated(e);
            var q = Biencucbo.QuyenDangChon;
            if (q == null) return;
            if ((bool)q.Them == true)
            {
                btnnew.Visibility = DevExpress.XtraBars.BarItemVisibility.Always;
            }
            else
            {
                btnnew.Visibility = DevExpress.XtraBars.BarItemVisibility.Never;
            }
            if ((bool)q.Sua == true)
            {
                btnsua.Visibility = DevExpress.XtraBars.BarItemVisibility.Always;
            }
            else
            {
                btnsua.Visibility = DevExpress.XtraBars.BarItemVisibility.Never;
            }
            if ((bool)q.Xoa == true)
            {
                btnxoa.Visibility = DevExpress.XtraBars.BarItemVisibility.Always;
            }
            else
            {
                btnxoa.Visibility = DevExpress.XtraBars.BarItemVisibility.Never;
            }
        }
        //load
        public void load()
        {
            var check = (from a in db.pxuats where a.link == Biencucbo.thanhtoan select a);
            if (check.Count() == 0)
            {
                btnload.Enabled = false;
                Biencucbo.hdpx = 0;
                txt1.Enabled = false;
                gia.Enabled = false;
                db = new KetNoiDBDataContext();
                txtid.DataBindings.Clear();
                txtid.Text = "YYYYY";
                gcchitiet.DataSource = new DAL.KetNoiDBDataContext().View_xuatkhos;
                for (int i = 0; i <= gridView1.RowCount - 1; i++)
                {
                    gridView1.DeleteRow(i);
                }
                txtdv.Text = Biencucbo.donvi;
                txtngaylap.DateTime = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day);
                txtphongban.Text = Biencucbo.phongban;
                txtidnv.Text = Biencucbo.idnv.Trim();
                lbltennv.Text = Biencucbo.ten;
                //txtngaylap.Focus();
                txtloaihd.Focus();
                txtiddt.Text = Biencucbo.iddt;
                try
                {
                    var lst2 = (from a in db.doituongs select a).Single(t => t.id == txtiddt.Text);
                    lbltendt.Text = lst2.ten.ToString();
                    txtdiachi.Text = lst2.diachi.ToString();
                }
                catch (Exception)
                {
                }
                var lst = (from a in db.banhangcts where a.idbanhang == Biencucbo.thanhtoan select a);
                gridControl3.DataSource = lst;
                for (int i = 0; i < gridView18.RowCount; i++)
                {
                    gridView1.AddNewRow();
                    gridView1.SetFocusedRowCellValue("diengiai", "");
                    gridView1.SetFocusedRowCellValue("idsanpham", gridView18.GetRowCellValue(i, "idsanpham"));
                    gridView1.SetFocusedRowCellValue("soluong", gridView18.GetRowCellValue(i, "soluong"));
                    gridView1.SetFocusedRowCellValue("chietkhau", gridView18.GetRowCellValue(i, "chietkhau"));
                    gridView1.SetFocusedRowCellValue("thue", 0);
                    gridView1.SetFocusedRowCellValue("tygia", 1);
                    gridView1.SetFocusedRowCellValue("loaithue", "");
                    gridView1.SetFocusedRowCellValue("tiente", "KIP");
                    gridView1.SetFocusedRowCellValue("idcv", "");
                }
                gridView1.UpdateCurrentRow();
                gridView1.PostEditor();
                try
                {
                    var lst2 = (from a in db.doituongs select a).Single(t => t.id == txtiddt.Text);
                    lbltendt.Text = lst2.ten.ToString();
                    txtdiachi.Text = lst2.diachi.ToString();
                }
                catch (Exception)
                {
                }
               
                txtloaihd.Text = "Xuất bán - ຈ່າຍອອກຂາຍ";
                txtghichu.Text = "";
                txttiente.Text = "KIP";
                txttygia.Text = "1";
                txtbanhang.Text = Biencucbo.thanhtoan;
                //btn
                btnnew.Enabled = false;
                btnmo.Enabled = false;
                btnLuu.Enabled = true;
                btnsua.Enabled = false;
                btnxoa.Enabled = false;
                btnin.Enabled = false;
                btnreload.Enabled = false;
                try
                {
                    var lst2 = (from a in db.doituongs select a).Single(t => t.id == txtiddt.Text);
                    lbltendt.Text = lst2.ten.ToString();
                    txtdiachi.Text = lst2.diachi.ToString();
                    txtid.ReadOnly = true;
                    txtdv.ReadOnly = true;
                }
                catch (Exception)
                {
                }
                //enabled
                txtghichu.ReadOnly = false;
                txtngaylap.ReadOnly = false;
                txtiddt.ReadOnly = false;
                txttiente.ReadOnly = false;
                txttygia.ReadOnly = true;
                txtngaylap.ReadOnly = false;
                txtloaihd.ReadOnly = false;
                gridView1.OptionsBehavior.Editable = true;
                gridView16.OptionsBehavior.Editable = false;
                gridView18.OptionsBehavior.Editable = true;
            }
            else
            {
                Biencucbo.hdpx = 2;
                txt1.Enabled = false;
                btnnew.Enabled = false;
                btnthemmoi.Enabled = false;
                btnLuu.Enabled = false;
                btnsua.Enabled = true;
                btnxoa.Enabled = true;
                btnin.Enabled = true;
                btnreload.Enabled = false;
                txtdv.ReadOnly = true;
                txtid.ReadOnly = true;
                txtdiachi.ReadOnly = true;
                txtidnv.ReadOnly = true;
                txtphongban.ReadOnly = true;
                txttiente.ReadOnly = true;
                txttygia.ReadOnly = true;
                // Enable
                txtghichu.ReadOnly = true;
                txtngaylap.ReadOnly = true;
                txtiddt.ReadOnly = true;
                txtloaihd.ReadOnly = true;
                gridView1.OptionsBehavior.Editable = false;
                try
                {
                    var check2 = (from a in db.pxuats select a).FirstOrDefault(t => t.link == Biencucbo.thanhtoan);
                    if (check2 == null) return;
                    
                    txtid.Text = check2.id;
                    txtidnv.Text = check2.idnv;
                    txtdv.Text = check2.iddv;
                    txtngaylap.DateTime = DateTime.Parse(check2.ngaylap.ToString());
                    txtiddt.Text = check2.iddt;
                    txtghichu.Text = check2.ghichu;
                    txt1.Text = check2.so.ToString();
                    txtbanhang.Text = check2.link;
                    txtloaihd.Text = check2.loaixuat;
                    txttiente.Text = check2.tiente;
                    txttygia.Text = check2.tygia.ToString();
                    gcchitiet.DataSource = check2.pxuatcts;
                }
                catch
                {
                }
            }
        }
        //Mở
        private void btnmo_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            db = new KetNoiDBDataContext();
            f_dsxk frm = new f_dsxk();
            frm.ShowDialog();
            if (Biencucbo.getID == 1)
            {
                //load hoa don
                try
                {
                    var lst = (from hd in db.pxuats select new { a = hd }).FirstOrDefault(x => x.a.id == Biencucbo.ma);
                    if (lst == null) return;
                    txtid.Text = lst.a.id;
                    txtidnv.Text = lst.a.idnv;
                    txtdv.Text = lst.a.iddv;
                    txtngaylap.DateTime = DateTime.Parse(lst.a.ngaylap.ToString());
                    txtiddt.Text = lst.a.iddt;
                    txtghichu.Text = lst.a.ghichu;
                    txtbanhang.Text = lst.a.link;
                    txttiente.Text = lst.a.tiente;
                    txttygia.Text = lst.a.tygia.ToString();
                    txt1.Text = lst.a.so.ToString();
                    txtloaihd.Text = lst.a.loaixuat;
                    gcchitiet.DataSource = lst.a.pxuatcts;
                    //btn
                    btnnew.Enabled = true;
                    btnsua.Enabled = true;
                    btnLuu.Enabled = false;
                    btnmo.Enabled = true;
                    btnxoa.Enabled = true;
                    btnin.Enabled = true;
                    btnreload.Enabled = false;
                }
                catch
                {
                }
            }
        }
        //Add new
        private void btnnew_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Biencucbo.hdpx = 0;
            txtid.DataBindings.Clear();
            txtid.Text = "YYYYY";
            gcchitiet.DataSource = new DAL.KetNoiDBDataContext().View_xuatkhos;
            for (int i = 0; i <= gridView1.RowCount - 1; i++)
            {
                gridView1.DeleteRow(i);
            }
            gridView1.AddNewRow();
            txtdv.Text = Biencucbo.donvi;
            txtngaylap.DateTime = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day);
            check = txtngaylap.DateTime;
            txtphongban.Text = Biencucbo.phongban;
            txtidnv.Text = Biencucbo.idnv.Trim();
            lbltennv.Text = Biencucbo.ten;
            //txtngaylap.Focus();
            txtloaihd.Focus();
            txtiddt.Text = "";
            lbltendt.Text = "";
            txtloaihd.Text = "";
            txtghichu.Text = "";
            txtbanhang.Text = "";
            txttiente.Text = "KIP";
            txttygia.Text = "1";
            //btn
            btnnew.Enabled = false;
            btnmo.Enabled = false;
            btnLuu.Enabled = true;
            btnsua.Enabled = false;
            btnxoa.Enabled = false;
            btnin.Enabled = false;
            btnreload.Enabled = false;
            //enabled
            txtghichu.ReadOnly = false;
            txtngaylap.ReadOnly = false;
            txtiddt.ReadOnly = false;
            txttiente.ReadOnly = false;
            txttygia.ReadOnly = true;
            txtloaihd.ReadOnly = false;
            gridView1.OptionsBehavior.Editable = true;
        }
        //public int checkabc (double? soluong)
        //{
        //    int check = 0;
        //    checksoluong = checksoluong + double.Parse(soluong.ToString()) ;
        //    if (checksoluong > 0 )
        //    {
        //        if( checkstt == 0 )
        //        {
        //            check = 1;
        //        }
        //        checkstt = 1;
        //    }
        //    else
        //    {
        //        check = 1;
        //    }
        //    return check;
        //}
        //public double checksl (double? soluong)
        //{
        //    double sl = 0;
        //    if(soluong > checkton)
        //    {
        //        sl = double.Parse(soluong.ToString()) - checkban;
        //        checkban = checkban - sl;
        //    }
        //    else
        //    {
        //        sl = checkban;
        //    }
        //    return sl;
        //}
        //Lưu
        public void luu()
        {
            t_history hs = new t_history();
            t_tudong td = new t_tudong();
            gridView1.UpdateCurrentRow();
            int check1 = 0;
            if (txtngaylap.Text == "" || txtiddt.Text == "" || txtloaihd.Text == "" || txttiente.Text == "" || txttygia.Text == "")
            {
                Lotus.MsgBox.ShowWarningDialog("Thông tin chưa đầy đủ - Vui lòng kiểm tra lại!");
            }
            else
            {
                try
                {
                    for (int i = 0; i <= gridView1.RowCount - 1; i++)
                    {
                        //re-check
                        if (gridView1.GetRowCellDisplayText(i, "soluong").ToString() == "" || gridView1.GetRowCellDisplayText(i, "dongia").ToString() == "" || gridView1.GetRowCellDisplayText(i, "chietkhau").ToString() == "")
                        {
                            check1 = 1;
                        }
                        else if (gridView1.GetRowCellDisplayText(i, "idsanpham").ToString() == "")
                        {
                            check1 = 2;
                        }
                    }
                }
                catch (Exception)
                {
                }
                if (check1 == 1)
                {
                    Lotus.MsgBox.ShowErrorDialog("Thông tin chi tiết sản phẩm chưa đầy đủ - Vui Lòng Kiểm Tra Lại");
                }
                else if (check1 == 2)
                {
                    Lotus.MsgBox.ShowErrorDialog("Mã sản phẩm không được để trống - Vui Lòng Kiểm Tra Lại");
                }
                else
                {
                    if (Biencucbo.hdpx == 0)
                    {
                        db = new KetNoiDBDataContext();
                        try
                        {
                            string check = "PX" + Biencucbo.donvi.Trim().ToString();
                            var lst1 = (from s in db.tudongs where s.maphieu == check select new { so = s.so }).ToList();
                            if (lst1.Count == 0)
                            {
                                int so;
                                so = 2;
                                td.themtudong(check, so, "PX", "Phiếu Xuất Kho");
                                txtid.Text = check + "_000001";
                                txt1.Text = "1";
                            }
                            else
                            {
                                int k;
                                txt1.DataBindings.Clear();
                                txt1.DataBindings.Add("text", lst1, "so");
                                k = 0;
                                k = Convert.ToInt32(txt1.Text);
                                string so0 = "";
                                if (k < 10)
                                {
                                    so0 = "00000";
                                }
                                else if (k >= 10 & k < 100)
                                {
                                    so0 = "0000";
                                }
                                else if (k >= 100 & k < 1000)
                                {
                                    so0 = "000";
                                }
                                else if (k >= 1000 & k < 10000)
                                {
                                    so0 = "00";
                                }
                                else if (k >= 10000 & k < 100000)
                                {
                                    so0 = "0";
                                }
                                else if (k >= 100000)
                                {
                                    so0 = "";
                                }
                                txtid.Text = check + "_" + so0 + k;
                                k = k + 1;
                                td.suatudong(check, k);
                            }
                            hd.moixk(txtid.Text, txtngaylap.DateTime, txtiddt.Text, txtidnv.Text, txtdv.Text, txtghichu.Text, Convert.ToInt32(txt1.Text), txtloaihd.Text, txttiente.Text, double.Parse(txttygia.Text), txtbanhang.Text);
                            for (int i = 0; i <= gridView1.RowCount - 1; i++)
                            {
                                gridView1.SetRowCellValue(i, "idpxuat", txtid.Text);
                                gridView1.SetRowCellValue(i, "id", txtid.Text + i);
                                hd.moixkct(gridView1.GetRowCellValue(i, "idpxuat").ToString(), gridView1.GetRowCellValue(i, "idsanpham").ToString(), gridView1.GetRowCellValue(i, "diengiai").ToString(), double.Parse(gridView1.GetRowCellValue(i, "soluong").ToString()), double.Parse(gridView1.GetRowCellValue(i, "dongia").ToString()), gridView1.GetRowCellValue(i, "loaithue").ToString(), double.Parse(gridView1.GetRowCellValue(i, "thue").ToString()), double.Parse(gridView1.GetRowCellValue(i, "chietkhau").ToString()), double.Parse(gridView1.GetRowCellValue(i, "thanhtien").ToString()), gridView1.GetRowCellValue(i, "id").ToString(), double.Parse(gridView1.GetRowCellValue(i, "nguyente").ToString()), gridView1.GetRowCellValue(i, "idcv").ToString());
                                if (txtloaihd.Text == "Xuất bán - ຈ່າຍອອກຂາຍ")
                                {
                                    tk.moi(txtid.Text + i + "1", txtdv.Text, "PX", txtid.Text, txtngaylap.DateTime, new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day), Convert.ToInt32(txt1.Text), txtiddt.Text, txtdv.Text, gridView1.GetRowCellValue(i, "diengiai").ToString(), "632", "1561", (double.Parse(gridView1.GetRowCellValue(i, "thanhtien").ToString())), txttiente.Text, double.Parse(txttygia.Text), double.Parse(gridView1.GetRowCellValue(i, "nguyente").ToString()), gridView1.GetRowCellValue(i, "idsanpham").ToString(), gridView1.GetRowCellValue(i, "id").ToString(), txtidnv.Text, txtloaihd.Text, gridView1.GetRowCellValue(i, "idcv").ToString(), "", lbltendt.Text, txtghichu.Text, double.Parse(gridView1.GetRowCellValue(i, "soluong").ToString()));
                                }
                                else if (txtloaihd.Text == "Điều chuyển nội bộ -ເຄື່ອນຍ້າຍພາຍໃນ")
                                {
                                    tk.moi(txtid.Text + i + "1", txtdv.Text, "PX", txtid.Text, txtngaylap.DateTime, new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day), Convert.ToInt32(txt1.Text), txtiddt.Text, txtdv.Text, gridView1.GetRowCellValue(i, "diengiai").ToString(), "1561", "1561", (double.Parse(gridView1.GetRowCellValue(i, "thanhtien").ToString())), txttiente.Text, double.Parse(txttygia.Text), double.Parse(gridView1.GetRowCellValue(i, "nguyente").ToString()), gridView1.GetRowCellValue(i, "idsanpham").ToString(), gridView1.GetRowCellValue(i, "id").ToString(), txtidnv.Text, txtloaihd.Text, gridView1.GetRowCellValue(i, "idcv").ToString(), "", lbltendt.Text, txtghichu.Text, double.Parse(gridView1.GetRowCellValue(i, "soluong").ToString()));
                                }
                                else if (txtloaihd.Text == "Xuất dùng - ຈ່າຍອອກໃຊ້")
                                {
                                    //tk.moi(txtid.Text + i + "1", txtdv.Text, "PX", txtid.Text, txtngaylap.DateTime, new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day), Convert.ToInt32(txt1.Text), txtiddt.Text, txtdv.Text, gridView1.GetRowCellValue(i, "diengiai").ToString(), "642", "1561", (double.Parse(gridView1.GetRowCellValue(i, "thanhtien").ToString())), txttiente.Text, double.Parse(txttygia.Text), double.Parse(gridView1.GetRowCellValue(i, "nguyente").ToString()), gridView1.GetRowCellValue(i, "idsanpham").ToString(), gridView1.GetRowCellValue(i, "id").ToString(), txtidnv.Text, txtloaihd.Text, gridView1.GetRowCellValue(i, "idcv").ToString(), "", lbltendt.Text, txtghichu.Text, double.Parse(gridView1.GetRowCellValue(i, "soluong").ToString()));
                                    tk.moi(txtid.Text + i + "1", txtdv.Text, "PX", txtid.Text, txtngaylap.DateTime, new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day), Convert.ToInt32(txt1.Text), txtiddt.Text, txtdv.Text, gridView1.GetRowCellValue(i, "diengiai").ToString(), "641", "1561", (double.Parse(gridView1.GetRowCellValue(i, "thanhtien").ToString())), txttiente.Text, double.Parse(txttygia.Text), double.Parse(gridView1.GetRowCellValue(i, "nguyente").ToString()), gridView1.GetRowCellValue(i, "idsanpham").ToString(), gridView1.GetRowCellValue(i, "id").ToString(), txtidnv.Text, txtloaihd.Text, gridView1.GetRowCellValue(i, "idcv").ToString(), "", lbltendt.Text, txtghichu.Text, double.Parse(gridView1.GetRowCellValue(i, "soluong").ToString()));
                                }
                                else if (txtloaihd.Text == "Xuất hao hụt - ຈ່າຍບົກແຫ້ງລະເຫີຍອາຍ")
                                {
                                    tk.moi(txtid.Text + i + "1", txtdv.Text, "PX", txtid.Text, txtngaylap.DateTime, new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day), Convert.ToInt32(txt1.Text), txtiddt.Text, txtdv.Text, gridView1.GetRowCellValue(i, "diengiai").ToString(), "1388", "1561", (double.Parse(gridView1.GetRowCellValue(i, "thanhtien").ToString())), txttiente.Text, double.Parse(txttygia.Text), double.Parse(gridView1.GetRowCellValue(i, "nguyente").ToString()), gridView1.GetRowCellValue(i, "idsanpham").ToString(), gridView1.GetRowCellValue(i, "id").ToString(), txtidnv.Text, txtloaihd.Text, gridView1.GetRowCellValue(i, "idcv").ToString(), "", lbltendt.Text, txtghichu.Text, double.Parse(gridView1.GetRowCellValue(i, "soluong").ToString()));
                                }
                            }
                            //btn
                            btnmo.Enabled = true;
                            btnnew.Enabled = true;
                            btnLuu.Enabled = false;
                            btnsua.Enabled = true;
                            btnxoa.Enabled = true;
                            btnin.Enabled = true;
                            btnreload.Enabled = false;
                            //enabled
                            txtghichu.ReadOnly = true;
                            txtngaylap.ReadOnly = true;
                            txtiddt.ReadOnly = true;
                            txtloaihd.ReadOnly = true;
                            txttiente.ReadOnly = true;
                            txttygia.ReadOnly = true;
                            gridView1.OptionsBehavior.Editable = false;
                            Biencucbo.hdpx = 2;
                            // History
                            hs.add(txtid.Text, "Thêm mới");
                        }
                        catch (Exception ex)
                        {
                            XtraMessageBox.Show(ex.Message);
                        }
                    }
                    else
                    {
                        try
                        {
                            hd.suaxk(txtid.Text, DateTime.Parse(txtngaylap.Text), txtiddt.Text, txtghichu.Text, int.Parse(txt1.Text), txtloaihd.Text, txttiente.Text, double.Parse(txttygia.Text), txtbanhang.Text);
                            //sua ct
                            LuuPhieu();
                            tk.xoa(txtid.Text);
                            for (int i = 0; i < gridView1.DataRowCount; i++)
                            {
                                if (txtloaihd.Text == "Xuất bán - ຈ່າຍອອກຂາຍ")
                                {
                                    tk.moi(txtid.Text + i + "1", txtdv.Text, "PX", txtid.Text, txtngaylap.DateTime, new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day), Convert.ToInt32(txt1.Text), txtiddt.Text, txtdv.Text, gridView1.GetRowCellValue(i, "diengiai").ToString(), "632", "1561", (double.Parse(gridView1.GetRowCellValue(i, "thanhtien").ToString())), txttiente.Text, double.Parse(txttygia.Text), double.Parse(gridView1.GetRowCellValue(i, "nguyente").ToString()), gridView1.GetRowCellValue(i, "idsanpham").ToString(), gridView1.GetRowCellValue(i, "id").ToString(), txtidnv.Text, txtloaihd.Text, gridView1.GetRowCellValue(i, "idcv").ToString(), "", lbltendt.Text, txtghichu.Text, double.Parse(gridView1.GetRowCellValue(i, "soluong").ToString()));
                                }
                                else if (txtloaihd.Text == "Điều chuyển nội bộ -ເຄື່ອນຍ້າຍພາຍໃນ")
                                {
                                    tk.moi(txtid.Text + i + "1", txtdv.Text, "PX", txtid.Text, txtngaylap.DateTime, new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day), Convert.ToInt32(txt1.Text), txtiddt.Text, txtdv.Text, gridView1.GetRowCellValue(i, "diengiai").ToString(), "1561", "1561", (double.Parse(gridView1.GetRowCellValue(i, "thanhtien").ToString())), txttiente.Text, double.Parse(txttygia.Text), double.Parse(gridView1.GetRowCellValue(i, "nguyente").ToString()), gridView1.GetRowCellValue(i, "idsanpham").ToString(), gridView1.GetRowCellValue(i, "id").ToString(), txtidnv.Text, txtloaihd.Text, gridView1.GetRowCellValue(i, "idcv").ToString(), "", lbltendt.Text, txtghichu.Text, double.Parse(gridView1.GetRowCellValue(i, "soluong").ToString()));
                                }
                                else if (txtloaihd.Text == "Xuất dùng - ຈ່າຍອອກໃຊ້")
                                {
                                    //tk.moi(txtid.Text + i + "1", txtdv.Text, "PX", txtid.Text, txtngaylap.DateTime, new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day), Convert.ToInt32(txt1.Text), txtiddt.Text, txtdv.Text, gridView1.GetRowCellValue(i, "diengiai").ToString(), "642", "1561", (double.Parse(gridView1.GetRowCellValue(i, "thanhtien").ToString())), txttiente.Text, double.Parse(txttygia.Text), double.Parse(gridView1.GetRowCellValue(i, "nguyente").ToString()), gridView1.GetRowCellValue(i, "idsanpham").ToString(), gridView1.GetRowCellValue(i, "id").ToString(), txtidnv.Text, txtloaihd.Text, gridView1.GetRowCellValue(i, "idcv").ToString(), "", lbltendt.Text, txtghichu.Text, double.Parse(gridView1.GetRowCellValue(i, "soluong").ToString()));
                                    tk.moi(txtid.Text + i + "1", txtdv.Text, "PX", txtid.Text, txtngaylap.DateTime, new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day), Convert.ToInt32(txt1.Text), txtiddt.Text, txtdv.Text, gridView1.GetRowCellValue(i, "diengiai").ToString(), "641", "1561", (double.Parse(gridView1.GetRowCellValue(i, "thanhtien").ToString())), txttiente.Text, double.Parse(txttygia.Text), double.Parse(gridView1.GetRowCellValue(i, "nguyente").ToString()), gridView1.GetRowCellValue(i, "idsanpham").ToString(), gridView1.GetRowCellValue(i, "id").ToString(), txtidnv.Text, txtloaihd.Text, gridView1.GetRowCellValue(i, "idcv").ToString(), "", lbltendt.Text, txtghichu.Text, double.Parse(gridView1.GetRowCellValue(i, "soluong").ToString()));
                                }
                                else if (txtloaihd.Text == "Xuất hao hụt - ຈ່າຍບົກແຫ້ງລະເຫີຍອາຍ")
                                {
                                    tk.moi(txtid.Text + i + "1", txtdv.Text, "PX", txtid.Text, txtngaylap.DateTime, new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day), Convert.ToInt32(txt1.Text), txtiddt.Text, txtdv.Text, gridView1.GetRowCellValue(i, "diengiai").ToString(), "1388", "1561", (double.Parse(gridView1.GetRowCellValue(i, "thanhtien").ToString())), txttiente.Text, double.Parse(txttygia.Text), double.Parse(gridView1.GetRowCellValue(i, "nguyente").ToString()), gridView1.GetRowCellValue(i, "idsanpham").ToString(), gridView1.GetRowCellValue(i, "id").ToString(), txtidnv.Text, txtloaihd.Text, gridView1.GetRowCellValue(i, "idcv").ToString(), "", lbltendt.Text, txtghichu.Text, double.Parse(gridView1.GetRowCellValue(i, "soluong").ToString()));
                                }
                            }
                            //btn
                            btnmo.Enabled = true;
                            btnnew.Enabled = true;
                            btnLuu.Enabled = false;
                            btnsua.Enabled = true;
                            btnxoa.Enabled = true;
                            btnin.Enabled = true;
                            btnreload.Enabled = false;
                            //enabled
                            txtghichu.ReadOnly = true;
                            txtngaylap.ReadOnly = true;
                            txtiddt.ReadOnly = true;
                            txtloaihd.ReadOnly = true;
                            txttiente.ReadOnly = true;
                            txttygia.ReadOnly = true;
                            gridView1.OptionsBehavior.Editable = false;
                            Biencucbo.hdpx = 2;
                            hs.add(txtid.Text, "Sửa");
                        }
                        catch (Exception ex)
                        {
                            XtraMessageBox.Show(ex.ToString());
                        }
                    }
                }
            }
        }
        private void btnLuu_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                gridView1.PostEditor();
                gridView1.UpdateCurrentRow();
                if (checkmadv == 0)
                {
                    Lotus.MsgBox.ShowWarningDialog("Đơn vị này chưa được tạo mã đối tượng - Vui lòng kiểm tra lại!");
                    return;
                }
                checkmasp = 1;
                for (int i = 0; i <= gridView1.RowCount - 1; i++)
                {
                    if (checkmasp == 1)
                    {
                        try
                        {
                            var lst = (from a in db.dmtks where a.sanpham == true && a.active == true && a.tkme == "156" select a).First(t => t.idsp == (gridView1.GetRowCellValue(i, "idsanpham").ToString()));
                            if (lst != null)
                                masp = lst.matk;
                                checkmasp = 1;
                        }
                        catch
                        {
                            checkmasp = 0;
                            masp = gridView1.GetRowCellValue(i, "idsanpham").ToString();
                        }
                    }
                }
                if (checkmasp == 0)
                {
                    Lotus.MsgBox.ShowWarningDialog("Sản phẩm " + masp + " chưa được tạo mã tài khoản - Vui lòng kiểm tra lại!");
                    return;
                }
                luu();
            }
            catch
            {
            }
        }
        bool LuuPhieu()
        {
            // kiem tra truoc khi luu
            layoutControl1.Validate();
            gridView1.CloseEditor();
            gridView1.UpdateCurrentRow();
            // if(kiem tra rang buoc)
            //  return false;
            try
            {
                var c1 = db.pxuats.Context.GetChangeSet();
                db.pxuatcts.Context.SubmitChanges();
            }
            catch (Exception ex)
            {
                XtraMessageBox.Show(ex.Message);
                return false;
            }
            return true;
        }
        DateTime check;
        private void btnsua_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            check = txtngaylap.DateTime;
            if (txtid.Text == "") return;
            try
            {
                var lst = (from pn in db.pxuats select pn).FirstOrDefault(x => x.id == txtid.Text);
                if (lst == null) return;
                gcchitiet.DataSource = lst.pxuatcts;
                //enabled
                txtghichu.ReadOnly = false;
                txtngaylap.ReadOnly = false;
                txtiddt.ReadOnly = false;
                txtloaihd.ReadOnly = false;
                txttiente.ReadOnly = false;
                txttygia.ReadOnly = true;
                gridView1.OptionsBehavior.Editable = true;
                Biencucbo.hdpx = 1;
                txtghichu.Focus();
                // btn
                btnsua.Enabled = false;
                btnLuu.Enabled = true;
                btnmo.Enabled = false;
                btnnew.Enabled = false;
                btnxoa.Enabled = false;
                btnin.Enabled = false;
                btnreload.Enabled = true;
            }
            catch
            {
            }
            //load 
        }
        private void btnxoa_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (XtraMessageBox.Show("Bạn có chắc chắn muốn xóa Hoá đơn " + txtid.Text + " không?", "THÔNG BÁO", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
            {
                t_history hs = new t_history();
                tk.xoa(txtid.Text);
                hs.add(txtid.Text, "Xóa");
                for (int i = gridView1.DataRowCount - 1; i >= 0; i--)
                {
                    hd.xoaxkct(gridView1.GetRowCellValue(i, "id").ToString());
                    gridView1.DeleteRow(i);
                }
                hd.xoaxk(txtid.Text);
                //btn
                btnmo.Enabled = true;
                btnnew.Enabled = true;
                btnLuu.Enabled = false;
                btnsua.Enabled = true;
                btnxoa.Enabled = true;
                btnin.Enabled = true;
                btnreload.Enabled = false;
                //enabled
                txtghichu.ReadOnly = true;
                txtngaylap.ReadOnly = true;
                txtiddt.ReadOnly = true;
                txtloaihd.ReadOnly = true;
                txttiente.ReadOnly = true;
                txttygia.ReadOnly = true;
                gridView1.OptionsBehavior.Editable = false;
                txtdv.Text = "";
                txtid.Text = "";
                txtidnv.Text = "";
                txtngaylap.Text = "";
                txtiddt.Text = "";
                txtghichu.Text = "";
                txtbanhang.Text = "";
                txt1.Text = "";
                txtloaihd.Text = "";
                lbltendt.Text = "";
                lbltennv.Text = "";
                txttiente.Text = "";
                txttygia.Text = "";
            }
        }
        private void btnin_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            var lst = (from a in db.r_pxuatkhos where a.id == txtid.Text select a);
            r_pxuat xtra = new r_pxuat();
            xtra.DataSource = lst;
            xtra.ShowPreviewDialog();
        }
        private void btnload_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (Biencucbo.hdpx == 1)
            {
                db = new KetNoiDBDataContext();
                var lst = (from pn in db.pxuats select pn).FirstOrDefault(x => x.id == txtid.Text);
                if (lst == null) return;
                //db.Refresh(RefreshMode.OverwriteCurrentValues, db.hoadoncts);
                txtidnv.Text = lst.idnv;
                txtdv.Text = lst.iddv;
                txtngaylap.DateTime = DateTime.Parse(lst.ngaylap.ToString());
                txtiddt.Text = lst.iddt;
                txtghichu.Text = lst.ghichu;
                txtbanhang.Text = lst.link;
                txt1.Text = lst.so.ToString();
                txtloaihd.Text = lst.loaixuat;
                txttiente.Text = lst.tiente;
                txttygia.Text = lst.tygia.ToString();
                gcchitiet.DataSource = lst.pxuatcts;
                //btn
                btnnew.Enabled = true;
                btnsua.Enabled = true;
                btnLuu.Enabled = false;
                btnmo.Enabled = true;
                btnxoa.Enabled = true;
                btnin.Enabled = true;
                btnreload.Enabled = false;
                gridView1.OptionsBehavior.Editable = false;
            }
            else if (Biencucbo.hdpx == 0)
            {
                load();
                btnnew.Enabled = true;
                btnsua.Enabled = true;
                btnLuu.Enabled = false;
                btnmo.Enabled = true;
                btnxoa.Enabled = true;
                btnin.Enabled = true;
                btnreload.Enabled = false;
                gridView1.OptionsBehavior.Editable = false;
            }
            Biencucbo.hdpx = 2;
        }
        private void btnmasp_EditValueChanged(object sender, EventArgs e)
        {
            try
            {
                gridView1.PostEditor();
                gridView1.UpdateCurrentRow();
                var tmua = (from a in db.r_pnhaps where a.ngaynhap <= txtngaylap.DateTime && a.iddv == Biencucbo.donvi && a.idsanpham == gridView1.GetFocusedRowCellValue("idsanpham").ToString() /*orderby a.so descending*/ select a);
                if (tmua.ToList().Count == 0)
                {
                    mua = 0;
                }
                else
                {
                    mua = double.Parse(tmua.Sum(t => t.soluong).ToString());
                }
                var tban = (from a in db.r_pxuatkhos where a.ngaylap <= txtngaylap.DateTime && a.iddv == Biencucbo.donvi && a.idsanpham == gridView1.GetFocusedRowCellValue("idsanpham").ToString() /*orderby a.so descending*/ select a);
                if (Biencucbo.hdpx == 0)
                {
                    tban = (from a in db.r_pxuatkhos where a.ngaylap <= txtngaylap.DateTime && a.iddv == Biencucbo.donvi && a.idsanpham == gridView1.GetFocusedRowCellValue("idsanpham").ToString() /*orderby a.so descending*/ select a);
                }
                else
                {
                    tban = (from a in db.r_pxuatkhos where a.ngaylap <= txtngaylap.DateTime && a.so < int.Parse(txt1.Text) && a.iddv == Biencucbo.donvi && a.idsanpham == gridView1.GetFocusedRowCellValue("idsanpham").ToString() /*orderby a.so descending*/ select a);
                }
                if (tban.ToList().Count == 0)
                {
                    ban = 0;
                }
                else
                {
                    ban = double.Parse(tban.Sum(t => t.soluong).ToString());
                }
                Biencucbo.tonxuat = mua - ban;
                Biencucbo.tonxuat2 = Biencucbo.tonxuat;
                //if (Biencucbo.tonxuat <= soluong3)
                //    soluong3 = Biencucbo.tonxuat;
                if (mua - (ban + double.Parse(gridView1.GetFocusedRowCellValue("soluong").ToString())) < 0)
                {
                    Lotus.MsgBox.ShowWarningDialog("Số lượng hàng tồn kho không đủ, không thể xuất kho - Vui lòng kiểm tra lại!");
                    gridView1.SetFocusedRowCellValue("idsanpham", "");
                    //gridView1.SetFocusedRowCellValue("soluong", 0);
                    return;
                }
                else
                {
                    var lst = (from a in db.r_pnhaps
                               where a.ngaynhap <= txtngaylap.DateTime && a.iddv == Biencucbo.donvi && a.idsanpham == gridView1.GetFocusedRowCellValue("idsanpham").ToString()
                               orderby a.so descending
                               select new
                               {
                                   idsanpham = a.idsanpham,
                                   a.soluong,
                                   dongia = (a.dongia == null ? 0 : a.dongia) - (a.chietkhau == null ? 0 : a.chietkhau),
                                   a.so,
                                   ngay = a.ngaynhap,
                               });
                    gridControl2.DataSource = lst;
                    gridView16.Columns["ngay"].SortOrder = DevExpress.Data.ColumnSortOrder.Descending;
                    ton.xoa(gridView1.GetFocusedRowCellValue("idsanpham").ToString(), Biencucbo.donvi, Biencucbo.idnv);
                    for (int i = 0; i < gridView16.DataRowCount; i++)
                    {
                        string a = "";
                        if (Biencucbo.tonxuat >= double.Parse(gridView16.GetRowCellValue(i, "soluong").ToString()))
                        {
                            a = gridView1.GetFocusedRowCellValue("idsanpham").ToString() + Biencucbo.donvi + Biencucbo.idnv + i;
                            ton.moi(a, Biencucbo.donvi, gridView1.GetFocusedRowCellValue("idsanpham").ToString(), float.Parse(gridView16.GetRowCellValue(i, "soluong").ToString()), float.Parse(gridView16.GetRowCellValue(i, "dongia").ToString()), int.Parse(gridView16.GetRowCellValue(i, "so").ToString()), Biencucbo.idnv, 0.0, DateTime.Parse(gridView16.GetRowCellValue(i, "ngay").ToString()));
                            Biencucbo.tonxuat = Biencucbo.tonxuat - double.Parse(gridView16.GetRowCellValue(i, "soluong").ToString());
                        }
                        else
                        {
                            if (Biencucbo.tonxuat != 0)
                            {
                                a = gridView1.GetFocusedRowCellValue("idsanpham").ToString() + Biencucbo.donvi + Biencucbo.idnv + i;
                                ton.moi(a, Biencucbo.donvi, gridView1.GetFocusedRowCellValue("idsanpham").ToString(), float.Parse(Biencucbo.tonxuat.ToString()), float.Parse(gridView16.GetRowCellValue(i, "dongia").ToString()), int.Parse(gridView16.GetRowCellValue(i, "so").ToString()), Biencucbo.idnv, 0.0, DateTime.Parse(gridView16.GetRowCellValue(i, "ngay").ToString()));
                                Biencucbo.tonxuat = 0;
                            }
                        }
                    }
                    //db = new KetNoiDBDataContext();
                    var lst2 = (from a in new DAL.KetNoiDBDataContext().tonsps
                                where a.idsp == gridView1.GetFocusedRowCellValue("idsanpham").ToString() && a.iddv == Biencucbo.donvi && a.idnv == Biencucbo.idnv
                                orderby a.so ascending
                                select new
                                {
                                    idsanpham = a.idsp,
                                    a.soluong,
                                    a.dongia,
                                    a.so,
                                    a.ngay,
                                });
                    gridControl2.DataSource = lst2;
                    gridView16.Columns["ngay"].SortOrder = DevExpress.Data.ColumnSortOrder.Ascending;
                    ton.xoa2(gridView1.GetFocusedRowCellValue("idsanpham").ToString(), Biencucbo.donvi, Biencucbo.idnv);
                    Biencucbo.tonxuat = double.Parse(gridView1.GetFocusedRowCellValue("soluong").ToString());
                    for (int i = 0; i < gridView16.DataRowCount; i++)
                    {
                        string a = "";
                        if (Biencucbo.tonxuat >= double.Parse(gridView16.GetRowCellValue(i, "soluong").ToString()))
                        {
                            a = gridView1.GetFocusedRowCellValue("idsanpham").ToString() + Biencucbo.donvi + Biencucbo.idnv + i;
                            ton.moi2(a, Biencucbo.donvi, gridView1.GetFocusedRowCellValue("idsanpham").ToString(), float.Parse(gridView16.GetRowCellValue(i, "soluong").ToString()), float.Parse(gridView16.GetRowCellValue(i, "dongia").ToString()), int.Parse(gridView16.GetRowCellValue(i, "so").ToString()), Biencucbo.idnv, 0.0, DateTime.Parse(gridView16.GetRowCellValue(i, "ngay").ToString()));
                            Biencucbo.tonxuat = Biencucbo.tonxuat - double.Parse(gridView16.GetRowCellValue(i, "soluong").ToString());
                        }
                        else
                        {
                            if (Biencucbo.tonxuat != 0)
                            {
                                a = gridView1.GetFocusedRowCellValue("idsanpham").ToString() + Biencucbo.donvi + Biencucbo.idnv + i;
                                ton.moi2(a, Biencucbo.donvi, gridView1.GetFocusedRowCellValue("idsanpham").ToString(), float.Parse(Biencucbo.tonxuat.ToString()), float.Parse(gridView16.GetRowCellValue(i, "dongia").ToString()), int.Parse(gridView16.GetRowCellValue(i, "so").ToString()), Biencucbo.idnv, 0.0, DateTime.Parse(gridView16.GetRowCellValue(i, "ngay").ToString()));
                                Biencucbo.tonxuat = 0;
                            }
                        }
                    }
                    //db = new KetNoiDBDataContext();
                    var lst3 = (from a in new DAL.KetNoiDBDataContext().tonsp2s
                                where a.idsp == gridView1.GetFocusedRowCellValue("idsanpham").ToString() && a.iddv == Biencucbo.donvi && a.idnv == Biencucbo.idnv
                                select new
                                {
                                    thanhtien = a.soluong * a.dongia
                                });
                    soluong3 = double.Parse(lst3.Sum(t => t.thanhtien).ToString()) / double.Parse(gridView1.GetFocusedRowCellValue("soluong").ToString());
                    gridView1.SetFocusedRowCellValue("dongia", soluong3);
                }
            }
            catch (Exception ex)
            {
                XtraMessageBox.Show(ex.ToString());
            }
        }
        private void gridView1_CellValueChanged(object sender, DevExpress.XtraGrid.Views.Base.CellValueChangedEventArgs e)
        {
            gridView1.PostEditor();
            gridView1.UpdateCurrentRow();
            if (e.Column.FieldName == "soluong" && double.Parse(gridView1.GetFocusedRowCellValue("soluong").ToString()) != 0)
            {
                //for (int i = 0; i <= gridView1.DataRowCount - 1; i++)
                //{
                var tmua = (from a in db.r_pnhaps where a.ngaynhap <= txtngaylap.DateTime && a.iddv == Biencucbo.donvi && a.idsanpham == gridView1.GetFocusedRowCellValue("idsanpham").ToString() /*orderby a.so descending*/ select a);
                if (tmua.ToList().Count == 0)
                {
                    mua = 0;
                }
                else
                {
                    mua = double.Parse(tmua.Sum(t => t.soluong).ToString());
                }
                var tban = (from a in db.r_pxuatkhos where a.ngaylap <= txtngaylap.DateTime && a.iddv == Biencucbo.donvi && a.idsanpham == gridView1.GetFocusedRowCellValue("idsanpham").ToString() /*orderby a.so descending*/ select a);
                if (Biencucbo.hdpx == 0)
                {
                    tban = (from a in db.r_pxuatkhos where a.ngaylap <= txtngaylap.DateTime && a.iddv == Biencucbo.donvi && a.idsanpham == gridView1.GetFocusedRowCellValue("idsanpham").ToString() /*orderby a.so descending*/ select a);
                }
                else
                {
                    tban = (from a in db.r_pxuatkhos where a.ngaylap <= txtngaylap.DateTime && a.so < int.Parse(txt1.Text) && a.iddv == Biencucbo.donvi && a.idsanpham == gridView1.GetFocusedRowCellValue("idsanpham").ToString() /*orderby a.so descending*/ select a);
                }
                if (tban.ToList().Count == 0)
                {
                    ban = 0;
                }
                else
                {
                    ban = double.Parse(tban.Sum(t => t.soluong).ToString());
                }
                Biencucbo.tonxuat = mua - ban;
                Biencucbo.tonxuat2 = Biencucbo.tonxuat;
                //if (Biencucbo.tonxuat <= soluong3)
                //    soluong3 = Biencucbo.tonxuat;
                if (mua - (ban + double.Parse(gridView1.GetFocusedRowCellValue("soluong").ToString())) < 0)
                {
                    Lotus.MsgBox.ShowWarningDialog("Số lượng hàng tồn kho không đủ, không thể xuất kho - Vui lòng kiểm tra lại!");
                    gridView1.SetFocusedRowCellValue("soluong", 0);
                    return;
                }
                else
                {
                    var lst = (from a in db.r_pnhaps
                               where a.ngaynhap <= txtngaylap.DateTime && a.iddv == Biencucbo.donvi && a.idsanpham == gridView1.GetFocusedRowCellValue("idsanpham").ToString()
                               orderby a.so descending
                               select new
                               {
                                   idsanpham = a.idsanpham,
                                   a.soluong,
                                   dongia = (a.dongia == null ? 0 : a.dongia) - (a.chietkhau == null ? 0 : a.chietkhau),
                                   a.so,
                                   ngay = a.ngaynhap,
                               });
                    gridControl2.DataSource = lst;
                    gridView16.Columns["ngay"].SortOrder = DevExpress.Data.ColumnSortOrder.Descending;
                    ton.xoa(gridView1.GetFocusedRowCellValue("idsanpham").ToString(), Biencucbo.donvi, Biencucbo.idnv);
                    for (int i = 0; i < gridView16.DataRowCount; i++)
                    {
                        string a = "";
                        if (Biencucbo.tonxuat >= double.Parse(gridView16.GetRowCellValue(i, "soluong").ToString()))
                        {
                            a = gridView1.GetFocusedRowCellValue("idsanpham").ToString() + Biencucbo.donvi + Biencucbo.idnv + i;
                            ton.moi(a, Biencucbo.donvi, gridView1.GetFocusedRowCellValue("idsanpham").ToString(), float.Parse(gridView16.GetRowCellValue(i, "soluong").ToString()), float.Parse(gridView16.GetRowCellValue(i, "dongia").ToString()), int.Parse(gridView16.GetRowCellValue(i, "so").ToString()), Biencucbo.idnv, 0.0, DateTime.Parse(gridView16.GetRowCellValue(i, "ngay").ToString()));
                            Biencucbo.tonxuat = Biencucbo.tonxuat - double.Parse(gridView16.GetRowCellValue(i, "soluong").ToString());
                        }
                        else
                        {
                            if (Biencucbo.tonxuat != 0)
                            {
                                a = gridView1.GetFocusedRowCellValue("idsanpham").ToString() + Biencucbo.donvi + Biencucbo.idnv + i;
                                ton.moi(a, Biencucbo.donvi, gridView1.GetFocusedRowCellValue("idsanpham").ToString(), float.Parse(Biencucbo.tonxuat.ToString()), float.Parse(gridView16.GetRowCellValue(i, "dongia").ToString()), int.Parse(gridView16.GetRowCellValue(i, "so").ToString()), Biencucbo.idnv, 0.0, DateTime.Parse(gridView16.GetRowCellValue(i, "ngay").ToString()));
                                Biencucbo.tonxuat = 0;
                            }
                        }
                    }
                    //db = new KetNoiDBDataContext();
                    var lst2 = (from a in new DAL.KetNoiDBDataContext().tonsps
                                where a.idsp == gridView1.GetFocusedRowCellValue("idsanpham").ToString() && a.iddv == Biencucbo.donvi && a.idnv == Biencucbo.idnv
                                orderby a.so ascending
                                select new
                                {
                                    idsanpham = a.idsp,
                                    a.soluong,
                                    a.dongia,
                                    a.so,
                                    a.ngay,
                                });
                    gridControl2.DataSource = lst2;
                    gridView16.Columns["ngay"].SortOrder = DevExpress.Data.ColumnSortOrder.Ascending;
                    ton.xoa2(gridView1.GetFocusedRowCellValue("idsanpham").ToString(), Biencucbo.donvi, Biencucbo.idnv);
                    Biencucbo.tonxuat = double.Parse(gridView1.GetFocusedRowCellValue("soluong").ToString());
                    for (int i = 0; i < gridView16.DataRowCount; i++)
                    {
                        string a = "";
                        if (Biencucbo.tonxuat >= double.Parse(gridView16.GetRowCellValue(i, "soluong").ToString()))
                        {
                            a = gridView1.GetFocusedRowCellValue("idsanpham").ToString() + Biencucbo.donvi + Biencucbo.idnv + i;
                            ton.moi2(a, Biencucbo.donvi, gridView1.GetFocusedRowCellValue("idsanpham").ToString(), float.Parse(gridView16.GetRowCellValue(i, "soluong").ToString()), float.Parse(gridView16.GetRowCellValue(i, "dongia").ToString()), int.Parse(gridView16.GetRowCellValue(i, "so").ToString()), Biencucbo.idnv, 0.0, DateTime.Parse(gridView16.GetRowCellValue(i, "ngay").ToString()));
                            Biencucbo.tonxuat = Biencucbo.tonxuat - double.Parse(gridView16.GetRowCellValue(i, "soluong").ToString());
                        }
                        else
                        {
                            if (Biencucbo.tonxuat != 0)
                            {
                                a = gridView1.GetFocusedRowCellValue("idsanpham").ToString() + Biencucbo.donvi + Biencucbo.idnv + i;
                                ton.moi2(a, Biencucbo.donvi, gridView1.GetFocusedRowCellValue("idsanpham").ToString(), float.Parse(Biencucbo.tonxuat.ToString()), float.Parse(gridView16.GetRowCellValue(i, "dongia").ToString()), int.Parse(gridView16.GetRowCellValue(i, "so").ToString()), Biencucbo.idnv, 0.0, DateTime.Parse(gridView16.GetRowCellValue(i, "ngay").ToString()));
                                Biencucbo.tonxuat = 0;
                            }
                        }
                    }
                    //db = new KetNoiDBDataContext();
                    var lst3 = (from a in new DAL.KetNoiDBDataContext().tonsp2s
                                where a.idsp == gridView1.GetFocusedRowCellValue("idsanpham").ToString() && a.iddv == Biencucbo.donvi && a.idnv == Biencucbo.idnv
                                select new
                                {
                                    thanhtien = a.soluong * a.dongia
                                });
                    soluong3 = double.Parse(lst3.Sum(t => t.thanhtien).ToString()) / double.Parse(gridView1.GetFocusedRowCellValue("soluong").ToString());
                    gridView1.SetFocusedRowCellValue("dongia", soluong3);
                }
                #region
                //}
            }
            if (e.Column.FieldName == "soluong" || e.Column.FieldName == "dongia" || e.Column.FieldName == "chietkhau" || e.Column.FieldName == "loaithue" || e.Column.FieldName == "tygia")
            {
                try
                {
                    try
                    {
                        gridView1.SetFocusedRowCellValue("thue", (((double.Parse(gridView1.GetFocusedRowCellValue("soluong").ToString())) * (double.Parse(gridView1.GetFocusedRowCellValue("dongia").ToString()))) - ((double.Parse(gridView1.GetFocusedRowCellValue("soluong").ToString())) * (double.Parse(gridView1.GetFocusedRowCellValue("chietkhau").ToString())))) * double.Parse(gridView1.GetFocusedRowCellDisplayText("loaithue").ToString()) / 100);
                    }
                    catch
                    {
                        gridView1.SetFocusedRowCellValue("nguyente", (((double.Parse(gridView1.GetFocusedRowCellValue("soluong").ToString())) * (double.Parse(gridView1.GetFocusedRowCellValue("dongia").ToString()))) - ((double.Parse(gridView1.GetFocusedRowCellValue("soluong").ToString())) * (double.Parse(gridView1.GetFocusedRowCellValue("chietkhau").ToString())))) + double.Parse(gridView1.GetFocusedRowCellValue("thue").ToString()));
                    }
                    finally
                    {
                        gridView1.SetFocusedRowCellValue("thue", (((double.Parse(gridView1.GetFocusedRowCellValue("soluong").ToString())) * (double.Parse(gridView1.GetFocusedRowCellValue("dongia").ToString()))) - ((double.Parse(gridView1.GetFocusedRowCellValue("soluong").ToString())) * (double.Parse(gridView1.GetFocusedRowCellValue("chietkhau").ToString())))) * double.Parse(gridView1.GetFocusedRowCellDisplayText("loaithue").ToString()) / 100);
                        gridView1.SetFocusedRowCellValue("nguyente", (((double.Parse(gridView1.GetFocusedRowCellValue("soluong").ToString())) * (double.Parse(gridView1.GetFocusedRowCellValue("dongia").ToString()))) - ((double.Parse(gridView1.GetFocusedRowCellValue("soluong").ToString())) * (double.Parse(gridView1.GetFocusedRowCellValue("chietkhau").ToString())))) + double.Parse(gridView1.GetFocusedRowCellValue("thue").ToString()));
                    }
                }
                catch (Exception)
                {
                }
            }
            else if (e.Column.FieldName == "nguyente")
            {
                try
                {
                    gridView1.SetFocusedRowCellValue("thanhtien", (double.Parse(gridView1.GetFocusedRowCellValue("nguyente").ToString())) * (double.Parse(txttygia.Text)));
                }
                catch (Exception)
                {
                }
            }
        }
        #endregion
        private void gridView1_KeyDown(object sender, KeyEventArgs e)
        {
            if (Biencucbo.hdpx != 2)
            {
                if (e.KeyCode == Keys.Insert)
                {
                    gridView1.AddNewRow();
                }
                else if (e.KeyCode == Keys.Delete)
                {
                   
                    gridView1.DeleteRow(gridView1.FocusedRowHandle);
                }
            }
            else
            {
                if (e.KeyCode == Keys.F4)
                {
                    Biencucbo.ma = txtid.Text;
                    f_dinhkhoan frm = new f_dinhkhoan();
                    frm.ShowDialog();
                }
            }
        }
        private void txtiddt_EditValueChanged(object sender, EventArgs e)
        {
            try
            {
                var lst = (from a in db.doituongs select a).Single(t => t.id == txtiddt.Text);
                lbltendt.Text = lst.ten.ToString();
                txtdiachi.Text = lst.diachi.ToString();
            }
            catch (Exception)
            {
            }
        }
        private void btnthue_EditValueChanged(object sender, EventArgs e)
        {
            gridView1.PostEditor();
        }
        //add new row
        private void gridView1_InitNewRow(object sender, DevExpress.XtraGrid.Views.Grid.InitNewRowEventArgs e)
        {
            if (Biencucbo.hdpx == 1)
            {
                var ct = gridView1.GetFocusedRow() as pxuatct;
                if (ct == null) return;
                int i = 0, k = 0;
                string a;
                k = gridView1.DataRowCount;
                a = txtid.Text + k;
                for (i = 0; i <= gridView1.DataRowCount - 1;)
                {
                    if (a == gridView1.GetRowCellValue(i, "id").ToString())
                    {
                        k = k + 1;
                        a = txtid.Text + k;
                        i = 0;
                    }
                    else
                    {
                        i++;
                    }
                }
                ct.idpxuat = txtid.Text;
                ct.soluong = 0;
                ct.dongia = 0;
                ct.chietkhau = 0;
                ct.diengiai = "";
                ct.loaithue = "";
                ct.idcv = "";
                ct.thue = 0;
                ct.thanhtien = 0;
                ct.id = a;
                ct.tiente = "KIP";
                ct.tygia = 1;
                ct.nguyente = 0;
            }
            else
            {
                gridView1.SetFocusedRowCellValue("diengiai", "");
                gridView1.SetFocusedRowCellValue("soluong", 0);
                gridView1.SetFocusedRowCellValue("dongia", 0);
                gridView1.SetFocusedRowCellValue("chietkhau", 0);
                gridView1.SetFocusedRowCellValue("thue", 0);
                gridView1.SetFocusedRowCellValue("tygia", 1);
                gridView1.SetFocusedRowCellValue("loaithue", "");
                gridView1.SetFocusedRowCellValue("tiente", "KIP");
                gridView1.SetFocusedRowCellValue("idcv", "");
            }
        }
        private void f_hd_FormClosing(object sender, FormClosingEventArgs e)
        {
            if (Biencucbo.hdpx != 2)
            {
                var a = Lotus.MsgBox.ShowYesNoCancelDialog("Phiếu xuất này chưa được lưu - Bạn có muốn lưu Hoá đơn này trước khi thoát không?", "THÔNG BÁO");
                if (a == DialogResult.Yes)
                {
                    luu();
                }
                else if (a == DialogResult.Cancel) e.Cancel = true;
            }
        }
        private void rsearchtiente_EditValueChanged(object sender, EventArgs e)
        {
            gridView1.PostEditor();
            try
            {
                var lst = (from a in db.tientes select a).Single(t => t.tiente1 == gridView1.GetFocusedRowCellValue("tiente").ToString());
                if (lst == null) return;
                gridView1.SetFocusedRowCellValue("tygia", lst.tygia);
            }
            catch
            {
            }
        }
        private void btnIdSp_EditValueChanged(object sender, EventArgs e)
        {
            gridView1.PostEditor();
        }
        private void f_hd_Load(object sender, EventArgs e)
        {
            LanguageHelper.Translate(this);
            LanguageHelper.Translate(barManager1);
            this.Text = LanguageHelper.TranslateMsgString("." + Name + "_title", "Phiếu Xuất Bán Hàng").ToString();
            changeFont.Translate(this);
            changeFont.Translate(barManager1);
            load();
        }
        private void btnthanhtoan_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
        }
        private void txttiente_EditValueChanged(object sender, EventArgs e)
        {
            try
            {
                var lst = (from a in db.tientes select a).FirstOrDefault(t => t.tiente1 == txttiente.Text);
                txttygia.Text = lst.tygia.ToString();
                for (int i = 0; i <= gridView1.RowCount - 1; i++)
                {
                    try
                    {
                        gridView1.SetRowCellValue(i, "thanhtien", double.Parse(gridView1.GetRowCellValue(i, "nguyente").ToString()) * double.Parse(txttygia.Text));
                    }
                    catch
                    {
                    }
                }
            }
            catch
            {
            }
        }
        private void gia_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //f_giasp form = new f_giasp();
            //form.ShowDialog();
            //var lst = new DAL.KetNoiDBDataContext().r_giasps;
            //try
            //{
            //    var lst2 = (from a in lst where a.iddv == Biencucbo.donvi select new { id = a.idsp, tensp = a.tensp, dvt = a.dvt });
            //    if (lst2 == null) return;
            //    btnmasp.DataSource = lst2;
            //    rsearchTenSP.DataSource = btnmasp.DataSource;
            //    btndvt.DataSource = btnmasp.DataSource;
            //}
            //catch
            //{
            //}
        }
        private void txtngaylap_EditValueChanged(object sender, EventArgs e)
        {
            //for (int j = 0; j < gridView1.DataRowCount; j++)
            //{
            //    try
            //    {
            //        var tmua = (from a in db.r_pnhaps where a.ngaynhap <= txtngaylap.DateTime && a.iddv == Biencucbo.donvi && a.idsanpham == gridView1.GetRowCellValue(j,"idsanpham").ToString() /*orderby a.so descending*/ select a);
            //        if (tmua.ToList().Count == 0)
            //        {
            //            mua = 0;
            //        }
            //        else
            //        {
            //            mua = double.Parse(tmua.Sum(t => t.soluong).ToString());
            //        }
            //        var tban = (from a in db.r_pxuatkhos where a.ngaylap <= txtngaylap.DateTime && a.iddv == Biencucbo.donvi && a.idsanpham == gridView1.GetRowCellValue(j, "idsanpham").ToString() /*orderby a.so descending*/ select a);
            //        if (Biencucbo.hdpx == 0)
            //        {
            //            tban = (from a in db.r_pxuatkhos where a.ngaylap <= txtngaylap.DateTime && a.iddv == Biencucbo.donvi && a.idsanpham == gridView1.GetRowCellValue(j, "idsanpham").ToString() /*orderby a.so descending*/ select a);
            //        }
            //        else
            //        {
            //            tban = (from a in db.r_pxuatkhos where a.ngaylap <= txtngaylap.DateTime && a.so < int.Parse(txt1.Text) && a.iddv == Biencucbo.donvi && a.idsanpham == gridView1.GetRowCellValue(j, "idsanpham").ToString() /*orderby a.so descending*/ select a);
            //        }
            //        if (tban.ToList().Count == 0)
            //        {
            //            ban = 0;
            //        }
            //        else
            //        {
            //            ban = double.Parse(tban.Sum(t => t.soluong).ToString());
            //        }
            //        Biencucbo.tonxuat = mua - ban;
            //        Biencucbo.tonxuat2 = Biencucbo.tonxuat;
            //        //if (Biencucbo.tonxuat <= soluong3)
            //        //    soluong3 = Biencucbo.tonxuat;
            //        if (mua - (ban + double.Parse(gridView1.GetRowCellValue(j, "soluong").ToString())) < 0)
            //        {
            //            Lotus.MsgBox.ShowWarningDialog("Số lượng hàng tồn kho không đủ, không thể xuất kho - Vui lòng kiểm tra lại!");
            //            txtngaylap.Undo();
            //            //gridView1.SetFocusedRowCellValue("soluong", 0);
            //            return;
            //        }
            //        else
            //        {
            //            var lst = (from a in db.r_pnhaps
            //                       where a.ngaynhap <= txtngaylap.DateTime && a.iddv == Biencucbo.donvi && a.idsanpham == gridView1.GetRowCellValue(j, "idsanpham").ToString()
            //                       orderby a.so descending
            //                       select new
            //                       {
            //                           idsanpham = a.idsanpham,
            //                           a.soluong,
            //                           a.dongia,
            //                           a.so,
            //                       });
            //            gridControl2.DataSource = lst;
            //            gridView16.Columns["so"].SortOrder = DevExpress.Data.ColumnSortOrder.Descending;
            //            ton.xoa(gridView1.GetRowCellValue(j, "idsanpham").ToString(), Biencucbo.donvi, Biencucbo.idnv);
            //            for (int i = 0; i < gridView16.DataRowCount; i++)
            //            {
            //                string a = "";
            //                if (Biencucbo.tonxuat >= double.Parse(gridView16.GetRowCellValue(i, "soluong").ToString()))
            //                {
            //                    a = gridView1.GetRowCellValue(j, "idsanpham").ToString() + Biencucbo.donvi + Biencucbo.idnv + i;
            //                    ton.moi(a, Biencucbo.donvi, gridView1.GetRowCellValue(j, "idsanpham").ToString(), float.Parse(gridView16.GetRowCellValue(i, "soluong").ToString()), float.Parse(gridView16.GetRowCellValue(i, "dongia").ToString()), int.Parse(gridView16.GetRowCellValue(i, "so").ToString()), Biencucbo.idnv);
            //                    Biencucbo.tonxuat = Biencucbo.tonxuat - double.Parse(gridView16.GetRowCellValue(i, "soluong").ToString());
            //                }
            //                else
            //                {
            //                    if (Biencucbo.tonxuat != 0)
            //                    {
            //                        a = gridView1.GetRowCellValue(j, "idsanpham").ToString() + Biencucbo.donvi + Biencucbo.idnv + i;
            //                        ton.moi(a, Biencucbo.donvi, gridView1.GetRowCellValue(j, "idsanpham").ToString(), float.Parse(Biencucbo.tonxuat.ToString()), float.Parse(gridView16.GetRowCellValue(i, "dongia").ToString()), int.Parse(gridView16.GetRowCellValue(i, "so").ToString()), Biencucbo.idnv);
            //                        Biencucbo.tonxuat = 0;
            //                    }
            //                }
            //            }
            //            db = new KetNoiDBDataContext();
            //            var lst2 = (from a in db.tonsps
            //                        where a.idsp == gridView1.GetRowCellValue(j, "idsanpham").ToString() && a.iddv == Biencucbo.donvi && a.idnv == Biencucbo.idnv
            //                        orderby a.so ascending
            //                        select new
            //                        {
            //                            idsanpham = a.idsp,
            //                            a.soluong,
            //                            a.dongia,
            //                            a.so,
            //                        });
            //            gridControl2.DataSource = lst2;
            //            gridView16.Columns["so"].SortOrder = DevExpress.Data.ColumnSortOrder.Ascending;
            //            ton.xoa2(gridView1.GetRowCellValue(j, "idsanpham").ToString(), Biencucbo.donvi, Biencucbo.idnv);
            //            Biencucbo.tonxuat = double.Parse(gridView1.GetRowCellValue(j, "soluong").ToString());
            //            for (int i = 0; i < gridView16.DataRowCount; i++)
            //            {
            //                string a = "";
            //                if (Biencucbo.tonxuat >= double.Parse(gridView16.GetRowCellValue(i, "soluong").ToString()))
            //                {
            //                    a = gridView1.GetRowCellValue(j, "idsanpham").ToString() + Biencucbo.donvi + Biencucbo.idnv + i;
            //                    ton.moi2(a, Biencucbo.donvi, gridView1.GetRowCellValue(j, "idsanpham").ToString(), float.Parse(gridView16.GetRowCellValue(i, "soluong").ToString()), float.Parse(gridView16.GetRowCellValue(i, "dongia").ToString()), int.Parse(gridView16.GetRowCellValue(i, "so").ToString()), Biencucbo.idnv);
            //                    Biencucbo.tonxuat = Biencucbo.tonxuat - double.Parse(gridView16.GetRowCellValue(i, "soluong").ToString());
            //                }
            //                else
            //                {
            //                    if (Biencucbo.tonxuat != 0)
            //                    {
            //                        a = gridView1.GetRowCellValue(j, "idsanpham").ToString() + Biencucbo.donvi + Biencucbo.idnv + i;
            //                        ton.moi2(a, Biencucbo.donvi, gridView1.GetRowCellValue(j, "idsanpham").ToString(), float.Parse(Biencucbo.tonxuat.ToString()), float.Parse(gridView16.GetRowCellValue(i, "dongia").ToString()), int.Parse(gridView16.GetRowCellValue(i, "so").ToString()), Biencucbo.idnv);
            //                        Biencucbo.tonxuat = 0;
            //                    }
            //                }
            //            }
            //            db = new KetNoiDBDataContext();
            //            var lst3 = (from a in db.tonsp2s
            //                        where a.idsp == gridView1.GetRowCellValue(j, "idsanpham").ToString() && a.iddv == Biencucbo.donvi && a.idnv == Biencucbo.idnv
            //                        select new
            //                        {
            //                            thanhtien = a.soluong * a.dongia
            //                        });
            //            soluong3 = double.Parse(lst3.Sum(t => t.thanhtien).ToString()) / double.Parse(gridView1.GetRowCellValue(j, "soluong").ToString());
            //            gridView1.SetFocusedRowCellValue("dongia", soluong3);
            //        }
            //    }
            //    catch
            //    {
            //    }
            //}
        }
        private void txtngaylap_Leave(object sender, EventArgs e)
        {
            for (int j = 0; j < gridView1.DataRowCount; j++)
            {
                try
                {
                    var tmua = (from a in db.r_pnhaps where a.ngaynhap <= txtngaylap.DateTime && a.iddv == Biencucbo.donvi && a.idsanpham == gridView1.GetRowCellValue(j, "idsanpham").ToString() /*orderby a.so descending*/ select a);
                    if (tmua.ToList().Count == 0)
                    {
                        mua = 0;
                    }
                    else
                    {
                        mua = double.Parse(tmua.Sum(t => t.soluong).ToString());
                    }
                    var tban = (from a in db.r_pxuatkhos where a.ngaylap <= txtngaylap.DateTime && a.iddv == Biencucbo.donvi && a.idsanpham == gridView1.GetRowCellValue(j, "idsanpham").ToString() /*orderby a.so descending*/ select a);
                    if (Biencucbo.hdpx == 0)
                    {
                        tban = (from a in db.r_pxuatkhos where a.ngaylap <= txtngaylap.DateTime && a.iddv == Biencucbo.donvi && a.idsanpham == gridView1.GetRowCellValue(j, "idsanpham").ToString() /*orderby a.so descending*/ select a);
                    }
                    else
                    {
                        tban = (from a in db.r_pxuatkhos where a.ngaylap <= txtngaylap.DateTime && a.so < int.Parse(txt1.Text) && a.iddv == Biencucbo.donvi && a.idsanpham == gridView1.GetRowCellValue(j, "idsanpham").ToString() /*orderby a.so descending*/ select a);
                    }
                    if (tban.ToList().Count == 0)
                    {
                        ban = 0;
                    }
                    else
                    {
                        ban = double.Parse(tban.Sum(t => t.soluong).ToString());
                    }
                    Biencucbo.tonxuat = mua - ban;
                    Biencucbo.tonxuat2 = Biencucbo.tonxuat;
                    //if (Biencucbo.tonxuat <= soluong3)
                    //    soluong3 = Biencucbo.tonxuat;
                    if (mua - (ban + double.Parse(gridView1.GetRowCellValue(j, "soluong").ToString())) < 0)
                    {
                        Lotus.MsgBox.ShowWarningDialog("Số lượng hàng tồn kho không đủ, không thể xuất kho - Vui lòng kiểm tra lại!");
                        txtngaylap.DateTime = check;
                        //gridView1.SetFocusedRowCellValue("soluong", 0);
                        return;
                    }
                    else
                    {
                        var lst = (from a in db.r_pnhaps
                                   where a.ngaynhap <= txtngaylap.DateTime && a.iddv == Biencucbo.donvi && a.idsanpham == gridView1.GetRowCellValue(j, "idsanpham").ToString()
                                   orderby a.so descending
                                   select new
                                   {
                                       idsanpham = a.idsanpham,
                                       a.soluong,
                                       dongia = (a.dongia == null ? 0 : a.dongia) - (a.chietkhau == null ? 0 : a.chietkhau),
                                       a.so,
                                       ngay = a.ngaynhap,
                                   });
                        gridControl2.DataSource = lst;
                        gridView16.Columns["ngay"].SortOrder = DevExpress.Data.ColumnSortOrder.Descending;
                        ton.xoa(gridView1.GetRowCellValue(j, "idsanpham").ToString(), Biencucbo.donvi, Biencucbo.idnv);
                        for (int i = 0; i < gridView16.DataRowCount; i++)
                        {
                            string a = "";
                            if (Biencucbo.tonxuat >= double.Parse(gridView16.GetRowCellValue(i, "soluong").ToString()))
                            {
                                a = gridView1.GetRowCellValue(j, "idsanpham").ToString() + Biencucbo.donvi + Biencucbo.idnv + i;
                                ton.moi(a, Biencucbo.donvi, gridView1.GetRowCellValue(j, "idsanpham").ToString(), float.Parse(gridView16.GetRowCellValue(i, "soluong").ToString()), float.Parse(gridView16.GetRowCellValue(i, "dongia").ToString()), int.Parse(gridView16.GetRowCellValue(i, "so").ToString()), Biencucbo.idnv, 0.0, DateTime.Parse(gridView16.GetRowCellValue(i, "ngay").ToString()));
                                Biencucbo.tonxuat = Biencucbo.tonxuat - double.Parse(gridView16.GetRowCellValue(i, "soluong").ToString());
                            }
                            else
                            {
                                if (Biencucbo.tonxuat != 0)
                                {
                                    a = gridView1.GetRowCellValue(j, "idsanpham").ToString() + Biencucbo.donvi + Biencucbo.idnv + i;
                                    ton.moi(a, Biencucbo.donvi, gridView1.GetRowCellValue(j, "idsanpham").ToString(), float.Parse(Biencucbo.tonxuat.ToString()), float.Parse(gridView16.GetRowCellValue(i, "dongia").ToString()), int.Parse(gridView16.GetRowCellValue(i, "so").ToString()), Biencucbo.idnv, 0.0, DateTime.Parse(gridView16.GetRowCellValue(i, "ngay").ToString()));
                                    Biencucbo.tonxuat = 0;
                                }
                            }
                        }
                        //db = new KetNoiDBDataContext();
                        var lst2 = (from a in new DAL.KetNoiDBDataContext().tonsps
                                    where a.idsp == gridView1.GetRowCellValue(j, "idsanpham").ToString() && a.iddv == Biencucbo.donvi && a.idnv == Biencucbo.idnv
                                    orderby a.so ascending
                                    select new
                                    {
                                        idsanpham = a.idsp,
                                        a.soluong,
                                        a.dongia,
                                        a.so,
                                        a.ngay
                                    });
                        gridControl2.DataSource = lst2;
                        gridView16.Columns["ngay"].SortOrder = DevExpress.Data.ColumnSortOrder.Ascending;
                        ton.xoa2(gridView1.GetRowCellValue(j, "idsanpham").ToString(), Biencucbo.donvi, Biencucbo.idnv);
                        Biencucbo.tonxuat = double.Parse(gridView1.GetRowCellValue(j, "soluong").ToString());
                        for (int i = 0; i < gridView16.DataRowCount; i++)
                        {
                            string a = "";
                            if (Biencucbo.tonxuat >= double.Parse(gridView16.GetRowCellValue(i, "soluong").ToString()))
                            {
                                a = gridView1.GetRowCellValue(j, "idsanpham").ToString() + Biencucbo.donvi + Biencucbo.idnv + i;
                                ton.moi2(a, Biencucbo.donvi, gridView1.GetRowCellValue(j, "idsanpham").ToString(), float.Parse(gridView16.GetRowCellValue(i, "soluong").ToString()), float.Parse(gridView16.GetRowCellValue(i, "dongia").ToString()), int.Parse(gridView16.GetRowCellValue(i, "so").ToString()), Biencucbo.idnv, 0.0, DateTime.Parse(gridView16.GetRowCellValue(i, "ngay").ToString()));
                                Biencucbo.tonxuat = Biencucbo.tonxuat - double.Parse(gridView16.GetRowCellValue(i, "soluong").ToString());
                            }
                            else
                            {
                                if (Biencucbo.tonxuat != 0)
                                {
                                    a = gridView1.GetRowCellValue(j, "idsanpham").ToString() + Biencucbo.donvi + Biencucbo.idnv + i;
                                    ton.moi2(a, Biencucbo.donvi, gridView1.GetRowCellValue(j, "idsanpham").ToString(), float.Parse(Biencucbo.tonxuat.ToString()), float.Parse(gridView16.GetRowCellValue(i, "dongia").ToString()), int.Parse(gridView16.GetRowCellValue(i, "so").ToString()), Biencucbo.idnv, 0.0, DateTime.Parse(gridView16.GetRowCellValue(i, "ngay").ToString()));
                                    Biencucbo.tonxuat = 0;
                                }
                            }
                        }
                        //db = new KetNoiDBDataContext();
                        var lst3 = (from a in new DAL.KetNoiDBDataContext().tonsp2s
                                    where a.idsp == gridView1.GetRowCellValue(j, "idsanpham").ToString() && a.iddv == Biencucbo.donvi && a.idnv == Biencucbo.idnv
                                    select new
                                    {
                                        thanhtien = a.soluong * a.dongia
                                    });
                        soluong3 = double.Parse(lst3.Sum(t => t.thanhtien).ToString()) / double.Parse(gridView1.GetRowCellValue(j, "soluong").ToString());
                        gridView1.SetFocusedRowCellValue("dongia", soluong3);
                    }
                }
                catch
                {
                }
            }
        }
        private void txtiddt_Popup(object sender, EventArgs e)
        {
            IPopupControl popupControl = sender as IPopupControl;
            SimpleButton button = new SimpleButton()
            {
                Image = Resources.icons8_Add_File_16,
                Text = "Thêm mới",
                BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder
            };
            button.Click += new EventHandler(button_Click);
            button.Location = new Point(5, popupControl.PopupWindow.Height - button.Height - 5);
            popupControl.PopupWindow.Controls.Add(button);
            button.BringToFront();
        }
        public void button_Click(object sender, EventArgs e)
        {
            f_doituong frm = new f_doituong();
            frm.ShowDialog();
            txtiddt.Properties.DataSource = new DAL.KetNoiDBDataContext().doituongs;
        }
        private void txttiente_Click(object sender, EventArgs e)
        {
        }
        private void txttiente_Popup(object sender, EventArgs e)
        {
            IPopupControl popupControl = sender as IPopupControl;
            SimpleButton button = new SimpleButton()
            {
                Image = Resources.icons8_Add_File_16,
                Text = "Edit",
                BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder
            };
            button.Click += new EventHandler(button_Click2);
            button.Location = new Point(5, popupControl.PopupWindow.Height - button.Height - 5);
            popupControl.PopupWindow.Controls.Add(button);
            button.BringToFront();
        }
        public void button_Click2(object sender, EventArgs e)
        {
            f_tiente2 frm = new f_tiente2();
            frm.ShowDialog();
            txttiente.Properties.DataSource = new KetNoiDBDataContext().tientes;
        }
        private void gridView1_RowDeleting(object sender, DevExpress.Data.RowDeletingEventArgs e)
        {
            if (Biencucbo.hdpx == 1)
            {
                try
                {
                    pxuatct ct = (from c in db.pxuatcts select c).Single(x => x.id == gridView1.GetFocusedRowCellValue("id").ToString());
                    db.pxuatcts.DeleteOnSubmit(ct);
                }
                catch
                {
                }
            }
        }
    }
}
