using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DAL;
using BUS;
using ControlLocalizer;
namespace GUI
{
    public partial class f_themgiaban : Form
    {
        KetNoiDBDataContext db = new KetNoiDBDataContext();
        t_gia sp = new t_gia();
        public f_themgiaban()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            txtid.Properties.DataSource = new DAL.KetNoiDBDataContext().sanphams;
            txtten.ReadOnly = true;
            if (Biencucbo.ngonngu.ToString() == "Vietnam")
            {
                gridColumn1.Caption = "Mã SP";
                gridColumn2.Caption = "Tên SP";
                gridColumn3.Caption = "ĐVT";
            }
            else //lao
            {
                gridColumn1.Caption = "ລະຫັດຜະລິດຕະພັນ";
                gridColumn2.Caption = "ຊື່ຜະລິດຕະພັນ";
                gridColumn3.Caption = "ຫົວໜ່ວຍຄິິດໄລ່";
            }
        }
        private void barButtonItem2_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            this.Close();
        }
        private void btnluu_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (txtid.Text == "" || txtten.Text == "" || txtchietkhau.Text == "")
            {
                Lotus.MsgBox.ShowWarningDialog("Thông tin chưa đầy đủ - Vui lòng kiểm tra lại!");
            }
            else
            {
                if (Biencucbo.hdgia == 0)
                {
                    //khong cho trung ID va Ten
                    var Lst = (from dt in db.giasps where dt.id == txtid.Text + "_" + Biencucbo.donvi select dt).ToList();
                    if (Lst.Count == 1)
                    {
                        Lotus.MsgBox.ShowErrorDialog("Sản phẩm này đã tồn tại, Vui Lòng Kiểm tra Lại");
                    }
                    else
                    {
                        sp.moi(txtid.Text + "_" + Biencucbo.donvi, Biencucbo.donvi, txtid.Text.Trim(), double.Parse(txtchietkhau.Text));
                        this.Close();
                    }
                }
                else
                {
                    sp.sua(txtid.Text + "_" + Biencucbo.donvi, Biencucbo.donvi, txtid.Text.Trim(), double.Parse(txtchietkhau.Text));
                    this.Close();
                }
            }
        }
        //load
        private void f_themsanpham_Load(object sender, EventArgs e)
        {
            LanguageHelper.Translate(this);
            LanguageHelper.Translate(barManager1);
            this.Text = LanguageHelper.TranslateMsgString("." + Name + "_title", "Thêm Giá Bán").ToString();
            changeFont.Translate(this);
            changeFont.Translate(barManager1);
            if (Biencucbo.hdmaspnhanh == 1)
            {
                var lst2 = (from a in db.giasps where a.idsp == Biencucbo.maspnhanh && a.iddv == Biencucbo.donvi select a).ToList();
                if (lst2.Count() == 0)
                {
                    txtid.Text = Biencucbo.maspnhanh;
                    Biencucbo.hdgia = 0;
                }
                else
                {
                    Biencucbo.hdgia = 1;
                    Biencucbo.ma = Biencucbo.maspnhanh;

                }
            }
            if (Biencucbo.hdgia == 1)
            {
                txtid.ReadOnly = true;
                txtten.ReadOnly = true;

                var lst = new DAL.KetNoiDBDataContext().r_giasps;
                var thucthi = (from k in lst select k).Single(t => t.idsp == Biencucbo.ma && t.iddv == Biencucbo.donvi);
                txtid.Text = thucthi.idsp;

                txtchietkhau.Text = thucthi.chietkhau.ToString();
            }
        }
        private void txtid_EditValueChanged(object sender, EventArgs e)
        {
            try
            {
                var lst = (from a in db.sanphams select a).Single(t => t.id == txtid.Text);
                txtten.Text = lst.tensp;

            }
            catch
            {
            }
        }
    }
}
