using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DAL;
using BUS;
using DevExpress.Utils.Win;
using DevExpress.XtraEditors;
using DevExpress.XtraBars;
using GUI.Properties;
using ControlLocalizer;
namespace GUI
{
    public partial class f_themdoituongbh : Form
    {
        KetNoiDBDataContext db = new KetNoiDBDataContext();
        t_doituongbh dt = new t_doituongbh();
        public f_themdoituongbh()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            txtnhom.Properties.DataSource = new DAL.KetNoiDBDataContext().nhomdoituongs;
            // This line of code is generated by Data Source Configuration Wizard
            txtmanv.Properties.DataSource = new DAL.KetNoiDBDataContext().accounts;
            txtmadv.Properties.DataSource = new DAL.KetNoiDBDataContext().donvis;
        }
        private void f_themdoituong_Load(object sender, EventArgs e)
        {
            LanguageHelper.Translate(this);
            LanguageHelper.Translate(barManager1);
            this.Text = LanguageHelper.TranslateMsgString("." + Name + "_title", "Thêm Đối Tượng").ToString();
            changeFont.Translate(this);
            changeFont.Translate(barManager1);
            if (Biencucbo.hdmanhanhdt == 1)
            {
                var lst2 = (from a in db.doituongbhs where a.id == Biencucbo.madtnhanh select a).ToList();
                if (lst2.Count() == 0)
                {
                    txtid.Text = Biencucbo.madtnhanh;
                    txtten.Text = Biencucbo.tennhanhdt;
                    Biencucbo.hddtbh = 0;
                }
                else
                {
                    Biencucbo.hddtbh = 1;
                    Biencucbo.ma = Biencucbo.madtnhanh;
                }
            }
            if (Biencucbo.hddtbh == 1)
            {
                txtid.Enabled = false;
                var Lst = (from dt in db.doituongbhs where dt.id == Biencucbo.ma select dt).ToList();
                txtid.DataBindings.Clear();
                txtten.DataBindings.Clear();
                txtnhom.DataBindings.Clear();
                txtloai.DataBindings.Clear();
                txtdc.DataBindings.Clear();
                txtmsthue.DataBindings.Clear();
                txtdt.DataBindings.Clear();
                txtdd.DataBindings.Clear();
                txtemail.DataBindings.Clear();
                txtfax.DataBindings.Clear();
                txttk.DataBindings.Clear();
                txtnh.DataBindings.Clear();
                txtmanv.DataBindings.Clear();
                txtmadv.DataBindings.Clear();
                txtid.DataBindings.Add("text", Lst, "id");
                txtid.Text.Trim();
                txtmanv.DataBindings.Add("text", Lst, "manv".Trim());
                txtmadv.DataBindings.Add("text", Lst, "madv".Trim());
                txtten.DataBindings.Add("text", Lst, "ten".Trim());
                txtnhom.DataBindings.Add("text", Lst, "nhom".Trim());
                txtloai.DataBindings.Add("text", Lst, "loai".Trim());
                txtdc.DataBindings.Add("text", Lst, "diachi".Trim());
                txtmsthue.DataBindings.Add("text", Lst, "msthue".Trim());
                txtdt.DataBindings.Add("text", Lst, "dienthoai".Trim());
                txtdd.DataBindings.Add("text", Lst, "dd".Trim());
                txtemail.DataBindings.Add("text", Lst, "email".Trim());
                txtfax.DataBindings.Add("text", Lst, "fax".Trim());
                txttk.DataBindings.Add("text", Lst, "taikhoan".Trim());
                txtnh.DataBindings.Add("text", Lst, "nganhang".Trim());
            }
        }
        private void txtnhom_Popup(object sender, EventArgs e)
        {
            //IPopupControl popupControl = sender as IPopupControl;
            //SimpleButton button = new SimpleButton()
            //{
            //    Image = Resources.icons8_Add_File_16,
            //    Text = "Thêm mới",
            //    BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder
            //};
            //button.Click += new EventHandler(button_Click);
            //button.Location = new Point(5, popupControl.PopupWindow.Height - button.Height - 5);
            //popupControl.PopupWindow.Controls.Add(button);
            //button.BringToFront();
        }
        //public void button_Click(object sender, EventArgs e)
        //{
        //    f_themnhomdoituong frm = new f_themnhomdoituong();
        //    frm.ShowDialog();
        //    txtnhom.Properties.DataSource = new KetNoiDBDataContext().nhomdoituongs;
        //}
        private void btnhuy_ItemClick(object sender, ItemClickEventArgs e)
        {
            this.Close();
        }
        private void luu_ItemClick(object sender, ItemClickEventArgs e)
        {
            if (txtid.Text == "" || txtten.Text == "" || txtnhom.Text == "")
            {
                Lotus.MsgBox.ShowWarningDialog("Thông tin chưa đầy đủ - Vui lòng kiểm tra lại!");
            }
            else
            {
                if (Biencucbo.hddtbh == 0)
                {
                    //khong cho trung ID va Ten
                    var Lst = (from dt in db.doituongbhs where dt.id == txtid.Text || dt.ten == txtten.Text select dt).ToList();
                    if (Lst.Count == 1)
                    {
                        Lotus.MsgBox.ShowErrorDialog("Đối tượng này đã tồn tại, Vui Lòng Kiểm tra Lại");
                    }
                    else
                    {
                        if(txtmanv.Text !="")
                        {
                            var lst2 = from a in db.doituongbhs where a.manv == txtmanv.Text select a;
                            if( lst2.Count() !=0)
                            {
                                Lotus.MsgBox.ShowErrorDialog("Mã nhân viên không được phép trùng, Vui Lòng Kiểm tra Lại");
                                return;
                            }
                        }
                        if (txtmadv.Text != "")
                        {
                            var lst2 = from a in db.doituongbhs where a.madv == txtmadv.Text select a;
                            if (lst2.Count() != 0)
                            {
                                Lotus.MsgBox.ShowErrorDialog("Mã đơn vị không được phép trùng, Vui Lòng Kiểm tra Lại");
                                return;
                            }
                        }
                        dt.moi(txtid.Text.Trim(), txtten.Text, txtnhom.Text, txtloai.Text, txtdc.Text, txtmsthue.Text, txtdt.Text, txtemail.Text, txtfax.Text, txtdd.Text, txttk.Text, txtnh.Text,txtmanv.Text, txtmadv.Text);
                        this.Close();
                    }
                }
                else
                {
                    var Lst = (from l in db.doituongbhs where l.ten == txtten.Text && l.id != txtid.Text select l).ToList();
                    if (Lst.Count == 1)
                    {
                        Lotus.MsgBox.ShowErrorDialog("Đối tượng này đã tồn tại, Vui Lòng Kiểm tra Lại");
                    }
                    else
                    {
                        dt.sua(txtid.Text, txtten.Text, txtnhom.Text, txtloai.Text, txtdc.Text, txtmsthue.Text, txtdt.Text, txtemail.Text, txtfax.Text, txtdd.Text, txttk.Text, txtnh.Text,txtmanv.Text, txtmadv.Text);
                        this.Close();
                    }
                }
            }
        }
    }
}
